//Just follow the logic.
var e=!0,k=null,l=!1,o=aMaurer,p=void 0;function aa(a,b,c){if(c===p&&1===a.nodeType)if(c="data-"+b.replace(ba,"-$1").toLowerCase(),c=a.getAttribute(c),"string"===typeof c){try{c="true"===c?e:"false"===c?l:"null"===c?k:q.nb(c)?+c:ca.test(c)?q.lc(c):c}catch(d){}q.data(a,b,c)}else c=p;return c}function da(a){for(var b in a)if(!("data"===b&&q.La(a[b]))&&"toJSON"!==b)return l;return e}
function ea(a,b,c){var d=b+"defer",f=b+"queue",g=b+"mark",i=q.c(a,d);i&&(("queue"===c||!q.c(a,f))&&("mark"===c||!q.c(a,g)))&&setTimeout(function(){!q.c(a,f)&&!q.c(a,g)&&(q.u(a,d,e),i.Rb())},0)}function r(){return l}function fa(){return e}
function ia(a,b,c){b=b||0;if(q.g(b))return q.R(a,function(a,d){return!!b.call(a,d,a)===c});if(b.nodeType)return q.R(a,function(a){return a===b===c});if("string"===typeof b){var d=q.R(a,function(a){return 1===a.nodeType});if(ja.test(b))return q.filter(b,d,!c);b=q.filter(b,d)}return q.R(a,function(a){return 0<=q.ea(a,b)===c})}function la(a){var b=ma.split("|"),a=a.createDocumentFragment();if(a.createElement)for(;b.length;)a.createElement(b.pop());return a}
function qa(a,b){if(1===b.nodeType&&q.Xb(a)){var c,d,f;d=q.c(a);var g=q.c(b,d),i=d.B;if(i)for(c in delete g.handle,g.B={},i){d=0;for(f=i[c].length;d<f;d++)q.event.add(b,c,i[c][d])}g.data&&(g.data=q.extend({},g.data))}}
function ra(a,b){var c;if(1===b.nodeType){b.Zc&&b.Zc();b.mergeAttributes&&b.mergeAttributes(a);c=b.nodeName.toLowerCase();if("object"===c)b.outerHTML=a.outerHTML;else if("input"===c&&("checkbox"===a.type||"radio"===a.type)){if(a.checked&&(b.defaultChecked=b.checked=a.checked),b.value!==a.value)b.value=a.value}else"option"===c?b.selected=a.defaultSelected:"input"===c||"textarea"===c?b.defaultValue=a.defaultValue:"script"===c&&b.text!==a.text&&(b.text=a.text);b.removeAttribute(q.expando);b.removeAttribute("_submit_attached");
b.removeAttribute("_change_attached")}}function sa(a){return"undefined"!==typeof a.getElementsByTagName?a.getElementsByTagName("*"):"undefined"!==typeof a.querySelectorAll?a.querySelectorAll("*"):[]}function ta(a){if("checkbox"===a.type||"radio"===a.type)a.defaultChecked=a.checked}function ua(a){var b=(a.nodeName||"").toLowerCase();"input"===b?ta(a):"script"!==b&&"undefined"!==typeof a.getElementsByTagName&&q.R(a.getElementsByTagName("input"),ta)}
function va(a,b,c){var d="width"===b?a.offsetWidth:a.offsetHeight,f="width"===b?1:0;if(0<d){if("border"!==c)for(;4>f;f+=2)c||(d-=parseFloat(q.e(a,"padding"+v[f]))||0),d="margin"===c?d+(parseFloat(q.e(a,c+v[f]))||0):d-(parseFloat(q.e(a,"border"+v[f]+"Width"))||0);return d+"px"}d=w(a,b);if(0>d||d==k)d=a.style[b];if(wa.test(d))return d;d=parseFloat(d)||0;if(c)for(;4>f;f+=2)d+=parseFloat(q.e(a,"padding"+v[f]))||0,"padding"!==c&&(d+=parseFloat(q.e(a,"border"+v[f]+"Width"))||0),"margin"===c&&(d+=parseFloat(q.e(a,
c+v[f]))||0);return d+"px"}function xa(a){return function(b,c){"string"!==typeof b&&(c=b,b="*");if(q.g(c))for(var d=b.toLowerCase().split(ya),f=0,g=d.length,i,h;f<g;f++)i=d[f],(h=/^\+/.test(i))&&(i=i.substr(1)||"*"),i=a[i]=a[i]||[],i[h?"unshift":"push"](c)}}
function za(a,b,c,d,f,g){f=f||b.t[0];g=g||{};g[f]=e;for(var f=a[f],i=0,h=f?f.length:0,j=a===Aa,m;i<h&&(j||!m);i++)m=f[i](b,c,d),"string"===typeof m&&(!j||g[m]?m=p:(b.t.unshift(m),m=za(a,b,c,d,m,g)));if((j||!m)&&!g["*"])m=za(a,b,c,d,"*",g);return m}function Ba(a,b){var c,d,f=q.M.kd||{};for(c in b)b[c]!==p&&((f[c]?a:d||(d={}))[c]=b[c]);d&&q.extend(e,a,d)}
function Ca(a,b,c,d){if(q.isArray(b))q.a(b,function(b,f){c||Da.test(a)?d(a,f):Ca(a+"["+("object"===typeof f?b:"")+"]",f,c,d)});else if(!c&&"object"===q.type(b))for(var f in b)Ca(a+"["+f+"]",b[f],c,d);else d(a,b)}function Ea(){try{return new o.XMLHttpRequest}catch(a){}}function Fa(){setTimeout(Ga,0);return Ha=q.now()}function Ga(){Ha=p}function x(a,b){var c={};q.a(Ia.concat.apply([],Ia.slice(0,b)),function(){c[this]=a});return c}
function La(a){if(!Ma[a]){var b=y.body,c=q("<"+a+">").Sc(b),d=c.e("display");c.remove();if("none"===d||""===d){E||(E=y.createElement("iframe"),E.frameBorder=E.width=E.height=0);b.appendChild(E);if(!H||!E.createElement)H=(E.contentaMaurer||E.contentDocument).document,H.write((q.b.X?"<!doctype html>":"")+"<html><body>"),H.close();c=H.createElement(a);H.body.appendChild(c);d=q.e(c,"display");b.removeChild(E)}Ma[a]=d}return Ma[a]}
function Na(a){return q.S(a)?a:9===a.nodeType?a.defaultView||a.parentaMaurer:l}var y=o.document,Oa=o.location,q;function Pa(){if(!I.pb){try{y.documentElement.doScroll("left")}catch(a){setTimeout(Pa,1);return}I.s()}}function I(a,b){return new I.d.fa(a,b,Qa)}
var Ra=o.v,Sa=o.Eb,Qa,Ta=/^(?:[^#<]*(<[\w\W]+>)[^>]*$|#([\w\-]*)$)/,Ua=/\S/,Va=/^\s+/,Wa=/\s+$/,Xa=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,Ya=/^[\],:{}\s]*$/,Za=/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,$a=/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,ab=/(?:^|:|,)(?:\s*\[)+/g,bb=/(webkit)[ \/]([\w.]+)/,cb=/(opera)(?:.*version)?[ \/]([\w.]+)/,db=/(msie) ([\w.]+)/,eb=/(mozilla)(?:.*? rv:([\w.]+))?/,fb=/-([a-z]|[0-9])/ig,gb=/^-ms-/;function lb(a,b){return(b+"").toUpperCase()}
var mb=o.navigator.userAgent,nb,ob,pb,qb=Object.prototype.toString,rb=Object.prototype.hasOwnProperty,sb=Array.prototype.push,tb=Array.prototype.slice,ub=String.prototype.trim,vb=Array.prototype.indexOf,wb={};
I.d=I.prototype={constructor:I,fa:function(a,b,c){var d;if(!a)return this;if(a.nodeType)return this.o=this[0]=a,this.length=1,this;if("body"===a&&!b&&y.body)return this.o=y,this[0]=y.body,this.j=a,this.length=1,this;if("string"===typeof a){if((d="<"===a.charAt(0)&&">"===a.charAt(a.length-1)&&3<=a.length?[k,a,k]:Ta.exec(a))&&(d[1]||!b)){if(d[1])return c=(b=b instanceof I?b[0]:b)?b.ownerDocument||b:y,(a=Xa.exec(a))?I.Ma(b)?(a=[y.createElement(a[1])],I.d.z.call(a,b,e)):a=[c.createElement(a[1])]:(a=I.Nb([d[1]],
[c]),a=(a.Ob?I.Y(a.Ia):a.Ia).childNodes),I.va(this,a);if((b=y.getElementById(d[2]))&&b.parentNode){if(b.id!==d[2])return c.find(a);this.length=1;this[0]=b}this.o=y;this.j=a;return this}return!b||b.v?(b||c).find(a):this.constructor(b).find(a)}if(I.g(a))return c.s(a);a.j!==p&&(this.j=a.j,this.o=a.o);return I.T(a,this)},j:"",v:"1.7.2",length:0,Ec:function(){return tb.call(this,0)},get:function(a){return a==k?this.Ec():0>a?this[this.length+a]:this[a]},q:function(a,b,c){var d=this.constructor();I.isArray(a)?
sb.apply(d,a):I.va(d,a);d.pc=this;d.o=this.o;"find"===b?d.j=this.j+(this.j?" ":"")+c:b&&(d.j=this.j+"."+b+"("+c+")");return d},a:function(a,b){return I.a(this,a,b)},s:function(a){I.Mb();ob.add(a);return this},Ha:function(a){a=+a;return-1===a?this.slice(a):this.slice(a,a+1)},jd:function(){return this.Ha(0)},Ad:function(){return this.Ha(-1)},slice:function(){return this.q(tb.apply(this,arguments),"slice",tb.call(arguments).join(","))},map:function(a){return this.q(I.map(this,function(b,c){return a.call(b,
c,b)}))},end:function(){return this.pc||this.constructor(k)},push:sb,sort:[].sort,splice:[].splice};I.d.fa.prototype=I.d;
I.extend=I.d.extend=function(){var a,b,c,d,f,g=arguments[0]||{},i=1,h=arguments.length,j=l;"boolean"===typeof g&&(j=g,g=arguments[1]||{},i=2);"object"!==typeof g&&!I.g(g)&&(g={});h===i&&(g=this,--i);for(;i<h;i++)if((a=arguments[i])!=k)for(b in a)c=g[b],d=a[b],g!==d&&(j&&d&&(I.Ma(d)||(f=I.isArray(d)))?(f?(f=l,c=c&&I.isArray(c)?c:[]):c=c&&I.Ma(c)?c:{},g[b]=I.extend(j,c,d)):d!==p&&(g[b]=d));return g};
I.extend({df:function(a){o.Eb===I&&(o.Eb=Sa);a&&o.v===I&&(o.v=Ra);return I},pb:l,xb:1,Re:function(a){a?I.xb++:I.s(e)},s:function(a){if(a===e&&!--I.xb||a!==e&&!I.pb){if(!y.body)return setTimeout(I.s,1);I.pb=e;a!==e&&0<--I.xb||(ob.sa(y,[I]),I.d.m&&I(y).m("ready").D("ready"))}},Mb:function(){if(!ob){ob=I.W("once memory");if("complete"===y.readyState)return setTimeout(I.s,1);if(y.addEventListener)y.addEventListener("DOMContentLoaded",pb,l),o.addEventListener("load",I.s,l);else if(y.attachEvent){y.attachEvent("onreadystatechange",
pb);o.attachEvent("onload",I.s);var a=l;try{a=o.frameElement==k}catch(b){}y.documentElement.doScroll&&a&&Pa()}}},g:function(a){return"function"===I.type(a)},isArray:Array.isArray||function(a){return"array"===I.type(a)},S:function(a){return a!=k&&a==a.aMaurer},nb:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},type:function(a){return a==k?String(a):wb[qb.call(a)]||"object"},Ma:function(a){if(!a||"object"!==I.type(a)||a.nodeType||I.S(a))return l;try{if(a.constructor&&!rb.call(a,"constructor")&&
!rb.call(a.constructor.prototype,"isPrototypeOf"))return l}catch(b){return l}for(var c in a);return c===p||rb.call(a,c)},La:function(a){for(var b in a)return l;return e},error:function(a){throw Error(a);},lc:function(a){if("string"!==typeof a||!a)return k;a=I.trim(a);if(o.JSON&&o.JSON.parse)return o.JSON.parse(a);if(Ya.test(a.replace(Za,"@").replace($a,"]").replace(ab,"")))return(new Function("return "+a))();I.error("Invalid JSON: "+a)},Jd:function(a){if("string"!==typeof a||!a)return k;var b,c;try{o.DOMParser?
(c=new DOMParser,b=c.parseFromString(a,"text/xml")):(b=new ActiveXObject("Microsoft.XMLDOM"),b.async="false",b.loadXML(a))}catch(d){b=p}(!b||!b.documentElement||b.getElementsByTagName("parsererror").length)&&I.error("Invalid XML: "+a);return b},hc:function(){},Wb:function(a){a&&Ua.test(a)&&(o.execScript||function(a){o.eval.call(o,a)})(a)},P:function(a){return a.replace(gb,"ms-").replace(fb,lb)},nodeName:function(a,b){return a.nodeName&&a.nodeName.toUpperCase()===b.toUpperCase()},a:function(a,b,c){var d,
f=0,g=a.length,i=g===p||I.g(a);if(c)if(i)for(d in a){if(b.apply(a[d],c)===l)break}else for(;f<g&&b.apply(a[f++],c)!==l;);else if(i)for(d in a){if(b.call(a[d],d,a[d])===l)break}else for(;f<g&&b.call(a[f],f,a[f++])!==l;);return a},trim:ub?function(a){return a==k?"":ub.call(a)}:function(a){return a==k?"":a.toString().replace(Va,"").replace(Wa,"")},T:function(a,b){var c=b||[];if(a!=k){var d=I.type(a);a.length==k||"string"===d||"function"===d||"regexp"===d||I.S(a)?sb.call(c,a):I.va(c,a)}return c},ea:function(a,
b,c){var d;if(b){if(vb)return vb.call(b,a,c);d=b.length;for(c=c?0>c?Math.max(0,d+c):c:0;c<d;c++)if(c in b&&b[c]===a)return c}return-1},va:function(a,b){var c=a.length,d=0;if("number"===typeof b.length)for(var f=b.length;d<f;d++)a[c++]=b[d];else for(;b[d]!==p;)a[c++]=b[d++];a.length=c;return a},R:function(a,b,c){for(var d=[],f,c=!!c,g=0,i=a.length;g<i;g++)f=!!b(a[g],g),c!==f&&d.push(a[g]);return d},map:function(a,b,c){var d,f,g=[],i=0,h=a.length;if(a instanceof I||h!==p&&"number"===typeof h&&(0<h&&
a[0]&&a[h-1]||0===h||I.isArray(a)))for(;i<h;i++)d=b(a[i],i,c),d!=k&&(g[g.length]=d);else for(f in a)d=b(a[f],f,c),d!=k&&(g[g.length]=d);return g.concat.apply([],g)},i:1,qf:function(a,b){function c(){return a.apply(b,f.concat(tb.call(arguments)))}if("string"===typeof b)var d=a[b],b=a,a=d;if(!I.g(a))return p;var f=tb.call(arguments,2);c.i=a.i=a.i||c.i||I.i++;return c},w:function(a,b,c,d,f,g,i){var h,j=c==k,m=0,n=a.length;if(c&&"object"===typeof c){for(m in c)I.w(a,b,m,c[m],1,g,d);f=1}else if(d!==p){h=
i===p&&I.g(d);j&&(h?(h=b,b=function(a,b,c){return h.call(I(a),c)}):(b.call(a,d),b=k));if(b)for(;m<n;m++)b(a[m],c,h?d.call(a[m],m,b(a[m],c)):d,i);f=1}return f?a:j?b.call(a):n?b(a[0],c):g},now:function(){return(new Date).getTime()},ge:function(a){a=a.toLowerCase();a=bb.exec(a)||cb.exec(a)||db.exec(a)||0>a.indexOf("compatible")&&eb.exec(a)||[];return{O:a[1]||"",version:a[2]||"0"}},sub:function(){function a(b,d){return new a.d.fa(b,d)}I.extend(e,a,this);a.Ff=this;a.d=a.prototype=this();a.d.constructor=
a;a.sub=this.sub;a.d.fa=function(c,d){d&&(d instanceof I&&!(d instanceof a))&&(d=a(d));return I.d.fa.call(this,c,d,b)};a.d.fa.prototype=a.d;var b=a(y);return a},O:{}});I.a("Boolean Number String Function Array Date RegExp Object".split(" "),function(a,b){wb["[object "+b+"]"]=b.toLowerCase()});nb=I.ge(mb);nb.O&&(I.O[nb.O]=e,I.O.version=nb.version);I.O.Qf&&(I.O.xf=e);Ua.test("\u00a0")&&(Va=/^[\s\xA0]+/,Wa=/[\s\xA0]+$/);Qa=I(y);
y.addEventListener?pb=function(){y.removeEventListener("DOMContentLoaded",pb,l);I.s()}:y.attachEvent&&(pb=function(){if(y.readyState==="complete"){y.detachEvent("onreadystatechange",pb);I.s()}});q=I;var xb={};
q.W=function(a){function b(b,c){c=c||[];m=!a.memory||[b,c];t=n=e;z=s||0;s=0;for(u=h.length;h&&z<u;z++)if(h[z].apply(b,c)===l&&a.Ef){m=e;break}t=l;if(h)if(a.jc)m===e?C.disable():h=[];else if(j&&j.length){m=j.shift();C.sa(m[0],m[1])}}function c(b){var d,f,g,i;d=0;for(f=b.length;d<f;d++){g=b[d];i=q.type(g);i==="array"?c(g):i==="function"&&(!a.unique||!C.lb(g))&&h.push(g)}}var d;if(a){if(!(d=xb[a])){d=a;var f=xb[d]={},g,i;d=d.split(/\s+/);g=0;for(i=d.length;g<i;g++)f[d[g]]=e;d=f}}else d={};var a=d,h=
[],j=[],m,n,t,s,u,z,C={add:function(){if(h){var a=h.length;c(arguments);if(t)u=h.length;else if(m&&m!==e){s=a;b(m[0],m[1])}}return this},remove:function(){if(h)for(var b=arguments,c=0,d=b.length;c<d;c++)for(var f=0;f<h.length;f++)if(b[c]===h[f]){if(t&&f<=u){u--;f<=z&&z--}h.splice(f--,1);if(a.unique)break}return this},lb:function(a){if(h)for(var b=0,c=h.length;b<c;b++)if(a===h[b])return e;return l},empty:function(){h=[];return this},disable:function(){h=j=m=p;return this},disabled:function(){return!h},
cc:function(){j=p;(!m||m===e)&&C.disable();return this},Ze:function(){return!j},sa:function(c,d){j&&(t?a.jc||j.push([c,d]):(!a.jc||!m)&&b(c,d));return this},Rb:function(){C.sa(this,arguments);return this},Sb:function(){return!!n}};return C};var yb=[].slice;
q.extend({Aa:function(a){var b=q.W("once memory"),c=q.W("once memory"),d=q.W("memory"),f="pending",g={Sd:b,sc:c,Gd:d},i={ba:b.add,ra:c.add,qc:d.add,state:function(){return f},xd:b.Sb,Ue:c.Sb,zb:function(a,b,c){h.ba(a).ra(b).qc(c);return this},Pc:function(){h.ba.apply(h,arguments).ra.apply(h,arguments);return this},mf:function(a,b,c){return q.Aa(function(d){q.a({ba:[a,"resolve"],ra:[b,"reject"],qc:[c,"notify"]},function(a,b){var c=b[0],f=b[1],g;if(q.g(c))h[a](function(){if((g=c.apply(this,arguments))&&
q.g(g.p))g.p().zb(d.Sd,d.sc,d.Gd);else d[f+"With"](this===h?d:this,[g])});else h[a](d[f])})}).p()},p:function(a){if(a==k)a=i;else for(var b in i)a[b]=i[b];return a}},h=i.p({}),j;for(j in g){h[j]=g[j].Rb;h[j+"With"]=g[j].sa}h.ba(function(){f="resolved"},c.disable,d.cc).ra(function(){f="rejected"},b.disable,d.cc);a&&a.call(h,h);return h},Rf:function(a){function b(a){return function(b){d[a]=arguments.length>1?yb.call(arguments,0):b;--h||j.Ua(j,d)}}function c(a){return function(b){i[a]=arguments.length>
1?yb.call(arguments,0):b;j.ff(m,i)}}var d=yb.call(arguments,0),f=0,g=d.length,i=Array(g),h=g,j=g<=1&&a&&q.g(a.p)?a:q.Aa(),m=j.p();if(g>1){for(;f<g;f++)d[f]&&d[f].p&&q.g(d[f].p)?d[f].p().zb(b(f),j.sc,c(f)):--h;h||j.Ua(j,d)}else j!==a&&j.Ua(j,g?[a]:[]);return m}});var zb=q,Ab;var K,Bb,Cb,Db,Eb,L,M,Fb,Gb,Hb,Ib,R=y.createElement("div");R.setAttribute("className","t");R.innerHTML="   <link/><table></table><a href='/a' style='top:1px;float:left;opacity:.55;'>a</a><input type='checkbox'/>";Bb=R.getElementsByTagName("*");
Cb=R.getElementsByTagName("a")[0];
if(!Bb||!Bb.length||!Cb)Ab={};else{Db=y.createElement("select");Eb=Db.appendChild(y.createElement("option"));L=R.getElementsByTagName("input")[0];K={bc:3===R.firstChild.nodeType,Dc:!R.getElementsByTagName("tbody").length,td:!!R.getElementsByTagName("link").length,style:/top/.test(Cb.getAttribute("style")),sd:"/a"===Cb.getAttribute("href"),opacity:/^0.55/.test(Cb.style.opacity),cssFloat:!!Cb.style.cssFloat,Yc:"on"===L.value,Id:Eb.selected,nd:"t"!==R.className,enctype:!!y.createElement("form").enctype,Yb:"<:nav></:nav>"!==
y.createElement("nav").cloneNode(e).outerHTML,ae:e,Xc:e,ld:l,Ga:e,ec:e,Zb:l,xc:l,tc:e,mc:e};q.X=K.X="CSS1Compat"===y.compatMode;L.checked=e;K.Fd=L.cloneNode(e).checked;Db.disabled=e;K.Hd=!Eb.disabled;try{delete R.test}catch(Jb){K.Ga=l}!R.addEventListener&&(R.attachEvent&&R.fireEvent)&&(R.attachEvent("onclick",function(){K.ec=l}),R.cloneNode(e).fireEvent("onclick"));L=y.createElement("input");L.value="t";L.setAttribute("type","radio");K.Pd="t"===L.value;L.setAttribute("checked","checked");L.setAttribute("name",
"t");R.appendChild(L);M=y.createDocumentFragment();M.appendChild(R.lastChild);K.Pb=M.cloneNode(e).cloneNode(e).lastChild.checked;K.Rc=L.checked;M.removeChild(L);M.appendChild(R);if(R.attachEvent)for(Hb in{submit:1,Wc:1,Le:1})Gb="on"+Hb,Ib=Gb in R,Ib||(R.setAttribute(Gb,"return;"),Ib="function"===typeof R[Gb]),K[Hb+"Bubbles"]=Ib;M.removeChild(R);M=Db=Eb=R=L=k;q(function(){var a,b,c,d,f=y.getElementsByTagName("body")[0];if(f){a=y.createElement("div");a.style.cssText="padding:0;margin:0;border:0;visibility:hidden;width:0;height:0;position:static;top:0;margin-top:1px";
f.insertBefore(a,f.firstChild);R=y.createElement("div");a.appendChild(R);R.innerHTML="<table><tr><td style='padding:0;margin:0;border:0;display:none'></td><td>t</td></tr></table>";Fb=R.getElementsByTagName("td");Ib=Fb[0].offsetHeight===0;Fb[0].style.display="";Fb[1].style.display="none";K.Qd=Ib&&Fb[0].offsetHeight===0;if(o.getComputedStyle){R.innerHTML="";b=y.createElement("div");b.style.width="0";b.style.marginRight="0";R.style.width="2px";R.appendChild(b);K.tc=(parseInt((o.getComputedStyle(b,k)||
{marginRight:0}).marginRight,10)||0)===0}if(typeof R.style.zoom!=="undefined"){R.innerHTML="";R.style.width=R.style.padding="1px";R.style.border=0;R.style.overflow="hidden";R.style.display="inline";R.style.zoom=1;K.Zb=R.offsetWidth===3;R.style.display="block";R.style.overflow="visible";R.innerHTML="<div style='width:5px;'></div>";K.xc=R.offsetWidth!==3}R.style.cssText="position:absolute;top:0;left:0;width:1px;height:1px;padding:0;margin:0;border:0;visibility:hidden;";R.innerHTML="<div style='position:absolute;top:0;left:0;width:1px;height:1px;padding:0;margin:0;border:5px solid #000;display:block;'><div style='padding:0;margin:0;border:0;display:block;overflow:hidden;'></div></div><table style='position:absolute;top:0;left:0;width:1px;height:1px;padding:0;margin:0;border:5px solid #000;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";
b=R.firstChild;c=b.firstChild;d=b.nextSibling.firstChild.firstChild;d={fd:c.offsetTop!==5,ed:d.offsetTop===5};c.style.position="fixed";c.style.top="20px";d.Ub=c.offsetTop===20||c.offsetTop===15;c.style.position=c.style.top="";b.style.overflow="hidden";b.style.position="relative";d.be=c.offsetTop===-5;d.gd=f.offsetTop!==1;if(o.getComputedStyle){R.style.marginTop="1%";K.mc=(o.getComputedStyle(R,k)||{marginTop:0}).marginTop!=="1%"}if(typeof a.style.zoom!=="undefined")a.style.zoom=1;f.removeChild(a);
R=k;q.extend(K,d)}});Ab=K}zb.b=Ab;var ca=/^(?:\{.*\}|\[.*\])$/,ba=/([A-Z])/g;
q.extend({G:{},ie:0,expando:"aQuery"+(q.d.v+Math.random()).replace(/\D/g,""),fc:{embed:e,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",applet:e},Xb:function(a){a=a.nodeType?q.G[a[q.expando]]:a[q.expando];return!!a&&!da(a)},data:function(a,b,c,d){if(q.Da(a)){var f;f=q.expando;var g=typeof b==="string",i=a.nodeType,h=i?q.G:a,j=i?a[f]:a[f]&&f,m=b==="events";if(j&&h[j]&&(m||d||h[j].data)||!(g&&c===p)){j||(i?a[f]=j=++q.ie:j=f);if(!h[j]){h[j]={};if(!i)h[j].toJSON=q.hc}if(typeof b==="object"||typeof b===
"function")d?h[j]=q.extend(h[j],b):h[j].data=q.extend(h[j].data,b);f=a=h[j];if(!d){if(!a.data)a.data={};a=a.data}c!==p&&(a[q.P(b)]=c);if(m&&!a[b])return f.B;if(g){c=a[b];c==k&&(c=a[q.P(b)])}else c=a;return c}}},u:function(a,b,c){if(q.Da(a)){var d,f,g,i=q.expando,h=a.nodeType,j=h?q.G:a,m=h?a[i]:i;if(j[m]){if(b)if(d=c?j[m]:j[m].data){if(!q.isArray(b))if(b in d)b=[b];else{b=q.P(b);b=b in d?[b]:b.split(" ")}f=0;for(g=b.length;f<g;f++)delete d[b[f]];if(!(c?da:q.La)(d))return}if(!c){delete j[m].data;if(!da(j[m]))return}q.b.Ga||
!j.setInterval?delete j[m]:j[m]=k;h&&(q.b.Ga?delete a[i]:a.removeAttribute?a.removeAttribute(i):a[i]=k)}}},c:function(a,b,c){return q.data(a,b,c,e)},Da:function(a){if(a.nodeName){var b=q.fc[a.nodeName.toLowerCase()];if(b)return!(b===e||a.getAttribute("classid")!==b)}return e}});
q.d.extend({data:function(a,b){var c,d,f,g,i,h=this[0],j=0,m=k;if(a===p){if(this.length){m=q.data(h);if(h.nodeType===1&&!q.c(h,"parsedAttrs")){f=h.attributes;for(i=f.length;j<i;j++){g=f[j].name;if(g.indexOf("data-")===0){g=q.P(g.substring(5));aa(h,g,m[g])}}q.c(h,"parsedAttrs",e)}}return m}if(typeof a==="object")return this.a(function(){q.data(this,a)});c=a.split(".",2);c[1]=c[1]?"."+c[1]:"";d=c[1]+"!";return q.w(this,function(b){if(b===p){m=this.Ab("getData"+d,[c[0]]);if(m===p&&h){m=q.data(h,a);m=
aa(h,a,m)}return m===p&&c[1]?this.data(c[0]):m}c[1]=b;this.a(function(){var f=q(this);f.Ab("setData"+d,c);q.data(this,a,b);f.Ab("changeData"+d,c)})},k,b,arguments.length>1,k,l)},u:function(a){return this.a(function(){q.u(this,a)})}});
q.extend({Lc:function(a,b){if(a){b=(b||"fx")+"mark";q.c(a,b,(q.c(a,b)||0)+1)}},Ib:function(a,b,c){if(a!==e){c=b;b=a;a=l}if(b){var c=c||"fx",d=c+"mark";if(a=a?0:(q.c(b,d)||1)-1)q.c(b,d,a);else{q.u(b,d,e);ea(b,c,"mark")}}},k:function(a,b,c){var d;if(a){b=(b||"fx")+"queue";d=q.c(a,b);c&&(!d||q.isArray(c)?d=q.c(a,b,q.T(c)):d.push(c));return d||[]}},$:function(a,b){var b=b||"fx",c=q.k(a,b),d=c.shift(),f={};d==="inprogress"&&(d=c.shift());if(d){b==="fx"&&c.unshift("inprogress");q.c(a,b+".run",f);d.call(a,
function(){q.$(a,b)},f)}if(!c.length){q.u(a,b+"queue "+b+".run",e);ea(a,b,"queue")}}});
q.d.extend({k:function(a,b){var c=2;if(typeof a!=="string"){b=a;a="fx";c--}return arguments.length<c?q.k(this[0],a):b===p?this:this.a(function(){var c=q.k(this,a,b);a==="fx"&&c[0]!=="inprogress"&&q.$(this,a)})},$:function(a){return this.a(function(){q.$(this,a)})},Ce:function(a,b){a=q.n?q.n.Wa[a]||a:a;return this.k(b||"fx",function(b,d){var f=setTimeout(b,a);d.stop=function(){clearTimeout(f)}})},we:function(a){return this.k(a||"fx",[])},p:function(a,b){function c(){--i||d.Ua(f,[f])}if(typeof a!==
"string"){b=a;a=p}for(var a=a||"fx",d=q.Aa(),f=this,g=f.length,i=1,h=a+"defer",j=a+"queue",m=a+"mark",n;g--;)if(n=q.data(f[g],h,p,e)||(q.data(f[g],j,p,e)||q.data(f[g],m,p,e))&&q.data(f[g],h,q.W("once memory"),e)){i++;n.add(c)}c();return d.p(b)}});
var Kb=/[\n\t\r]/g,Lb=/\s+/,Mb=/\r/g,Nb=/^(?:button|input)$/i,Ob=/^(?:button|input|object|select|textarea)$/i,Pb=/^a(?:rea)?$/i,Qb=/^(?:autofocus|autoplay|async|checked|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped|selected)$/i,Rb=q.b.nd,S,Sb,Tb;
q.d.extend({z:function(a,b){return q.w(this,q.z,a,b,arguments.length>1)},Ta:function(a){return this.a(function(){q.Ta(this,a)})},h:function(a,b){return q.w(this,q.h,a,b,arguments.length>1)},uf:function(a){a=q.xa[a]||a;return this.a(function(){try{this[a]=p;delete this[a]}catch(b){}})},Oc:function(a){var b,c,d,f,g,i,h;if(q.g(a))return this.a(function(b){q(this).Oc(a.call(this,b,this.className))});if(a&&typeof a==="string"){b=a.split(Lb);c=0;for(d=this.length;c<d;c++){f=this[c];if(f.nodeType===1)if(!f.className&&
b.length===1)f.className=a;else{g=" "+f.className+" ";i=0;for(h=b.length;i<h;i++)~g.indexOf(" "+b[i]+" ")||(g=g+(b[i]+" "));f.className=q.trim(g)}}}return this},Rd:function(a){var b,c,d,f,g,i,h;if(q.g(a))return this.a(function(b){q(this).Rd(a.call(this,b,this.className))});if(a&&typeof a==="string"||a===p){b=(a||"").split(Lb);c=0;for(d=this.length;c<d;c++){f=this[c];if(f.nodeType===1&&f.className)if(a){g=(" "+f.className+" ").replace(Kb," ");i=0;for(h=b.length;i<h;i++)g=g.replace(" "+b[i]+" "," ");
f.className=q.trim(g)}else f.className=""}}return this},fe:function(a,b){var c=typeof a,d=typeof b==="boolean";return q.g(a)?this.a(function(c){q(this).fe(a.call(this,c,this.className,b),b)}):this.a(function(){if(c==="string")for(var f,g=0,i=q(this),h=b,j=a.split(Lb);f=j[g++];){h=d?h:!i.qd(f);i[h?"addClass":"removeClass"](f)}else if(c==="undefined"||c==="boolean"){this.className&&q.c(this,"__className__",this.className);this.className=this.className||a===l?"":q.c(this,"__className__")||""}})},qd:function(a){for(var a=
" "+a+" ",b=0,c=this.length;b<c;b++)if(this[b].nodeType===1&&(" "+this[b].className+" ").replace(Kb," ").indexOf(a)>-1)return e;return l},V:function(a){var b,c,d,f=this[0];if(arguments.length){d=q.g(a);return this.a(function(c){var f=q(this);if(this.nodeType===1){c=d?a.call(this,c,f.V()):a;c==k?c="":typeof c==="number"?c=c+"":q.isArray(c)&&(c=q.map(c,function(a){return a==k?"":a+""}));b=q.J[this.type]||q.J[this.nodeName.toLowerCase()];if(!b||!("set"in b)||b.set(this,c,"value")===p)this.value=c}})}if(f){if((b=
q.J[f.type]||q.J[f.nodeName.toLowerCase()])&&"get"in b&&(c=b.get(f,"value"))!==p)return c;c=f.value;return typeof c==="string"?c.replace(Mb,""):c==k?"":c}}});
q.extend({J:{kc:{get:function(a){var b=a.attributes.value;return!b||b.specified?a.value:a.text}},select:{get:function(a){var b,c,d=a.selectedIndex,f=[],g=a.options,i=a.type==="select-one";if(d<0)return k;a=i?d:0;for(c=i?d+1:g.length;a<c;a++){b=g[a];if(b.selected&&(q.b.Hd?!b.disabled:b.getAttribute("disabled")===k)&&(!b.parentNode.disabled||!q.nodeName(b.parentNode,"optgroup"))){b=q(b).V();if(i)return b;f.push(b)}}return i&&!f.length&&g.length?q(g[d]).V():f},set:function(a,b){var c=q.T(b);q(a).find("option").a(function(){this.selected=
q.ea(q(this).V(),c)>=0});if(!c.length)a.selectedIndex=-1;return c}}},$a:{V:e,e:e,da:e,text:e,data:e,width:e,height:e,offset:e},z:function(a,b,c,d){var f,g,i=a.nodeType;if(a&&!(i===3||i===8||i===2)){if(d&&b in q.$a)return q(a)[b](c);if(typeof a.getAttribute==="undefined")return q.h(a,b,c);if(d=i!==1||!q.Oa(a)){b=b.toLowerCase();g=q.A[b]||(Qb.test(b)?Sb:S)}if(c!==p)if(c===k)q.Ta(a,b);else{if(g&&"set"in g&&d&&(f=g.set(a,c,b))!==p)return f;a.setAttribute(b,""+c);return c}else{if(g&&"get"in g&&d&&(f=g.get(a,
b))!==k)return f;f=a.getAttribute(b);return f===k?p:f}}},Ta:function(a,b){var c,d,f,g,i,h=0;if(b&&a.nodeType===1){d=b.toLowerCase().split(Lb);for(g=d.length;h<g;h++)if(f=d[h]){c=q.xa[f]||f;(i=Qb.test(f))||q.z(a,f,"");a.removeAttribute(Rb?f:c);i&&c in a&&(a[c]=l)}}},A:{type:{set:function(a,b){if(Nb.test(a.nodeName)&&a.parentNode)q.error("type property can't be changed");else if(!q.b.Pd&&b==="radio"&&q.nodeName(a,"input")){var c=a.value;a.setAttribute("type",b);if(c)a.value=c;return b}}},value:{get:function(a,
b){return S&&q.nodeName(a,"button")?S.get(a,b):b in a?a.value:k},set:function(a,b,c){if(S&&q.nodeName(a,"button"))return S.set(a,b,c);a.value=b}}},xa:{Cc:"tabIndex",sf:"readOnly","for":"htmlFor","class":"className",af:"maxLength",ue:"cellSpacing",te:"cellPadding",wf:"rowSpan",Ae:"colSpan",Of:"useMap",Me:"frameBorder",$c:"contentEditable"},h:function(a,b,c){var d,f,g;g=a.nodeType;if(a&&!(g===3||g===8||g===2)){if(g=g!==1||!q.Oa(a)){b=q.xa[b]||b;f=q.Sa[b]}return c!==p?f&&"set"in f&&(d=f.set(a,c,b))!==
p?d:a[b]=c:f&&"get"in f&&(d=f.get(a,b))!==k?d:a[b]}},Sa:{tabIndex:{get:function(a){var b=a.getAttributeNode("tabindex");return b&&b.specified?parseInt(b.value,10):Ob.test(a.nodeName)||Pb.test(a.nodeName)&&a.href?0:p}}}});q.A.Cc=q.Sa.tabIndex;Sb={get:function(a,b){var c,d=q.h(a,b);return d===e||typeof d!=="boolean"&&(c=a.getAttributeNode(b))&&c.nodeValue!==l?b.toLowerCase():p},set:function(a,b,c){if(b===l)q.Ta(a,c);else{b=q.xa[c]||c;b in a&&(a[b]=e);a.setAttribute(c,c.toLowerCase())}return c}};
Rb||(Tb={name:e,id:e,coords:e},S=q.J.button={get:function(a,b){var c;return(c=a.getAttributeNode(b))&&(Tb[b]?c.nodeValue!=="":c.specified)?c.nodeValue:p},set:function(a,b,c){var d=a.getAttributeNode(c);if(!d){d=y.createAttribute(c);a.setAttributeNode(d)}return d.nodeValue=b+""}},q.A.Cc.set=S.set,q.a(["width","height"],function(a,b){q.A[b]=q.extend(q.A[b],{set:function(a,d){if(d===""){a.setAttribute(b,"auto");return d}}})}),q.A.$c={get:S.get,set:function(a,b,c){b===""&&(b="false");S.set(a,b,c)}});
q.b.sd||q.a(["href","src","width","height"],function(a,b){q.A[b]=q.extend(q.A[b],{get:function(a){a=a.getAttribute(b,2);return a===k?p:a}})});q.b.style||(q.A.style={get:function(a){return a.style.cssText.toLowerCase()||p},set:function(a,b){return a.style.cssText=""+b}});q.b.Id||(q.Sa.selected=q.extend(q.Sa.selected,{get:function(a){if(a=a.parentNode){a.selectedIndex;a.parentNode&&a.parentNode.selectedIndex}return k}}));q.b.enctype||(q.xa.enctype="encoding");
q.b.Yc||q.a(["radio","checkbox"],function(){q.J[this]={get:function(a){return a.getAttribute("value")===k?"on":a.value}}});q.a(["radio","checkbox"],function(){q.J[this]=q.extend(q.J[this],{set:function(a,b){if(q.isArray(b))return a.checked=q.ea(q(a).V(),b)>=0}})});var Ub=/^(?:textarea|input|select)$/i,Vb=/^([^\.]*)?(?:\.(.+))?$/,Wb=/(?:^|\s)hover(\.\S+)?\b/,Xb=/^key/,Yb=/^(?:mouse|contextmenu)|click/,Zb=/^(?:focusinfocus|focusoutblur)$/,$b=/^(\w*)(?:#([\w\-]+))?(?:\.([\w\-]+))?$/;
function ac(a){if(a=$b.exec(a)){a[1]=(a[1]||"").toLowerCase();a[3]=a[3]&&RegExp("(?:^|\\s)"+a[3]+"(?:\\s|$)")}return a}function bc(a){return q.event.r.rd?a:a.replace(Wb,"mouseenter$1 mouseleave$1")}
q.event={add:function(a,b,c,d,f){var g,i,h,j,m,n,t,s,u;if(!(a.nodeType===3||a.nodeType===8||!b||!c||!(g=q.c(a)))){if(c.I){t=c;c=t.I;f=t.j}if(!c.i)c.i=q.i++;h=g.B;if(!h)g.B=h={};i=g.handle;if(!i){g.handle=i=function(a){return typeof q!=="undefined"&&(!a||q.event.Bb!==a.type)?q.event.hb.apply(i.f,arguments):p};i.f=a}b=q.trim(bc(b)).split(" ");for(g=0;g<b.length;g++){j=Vb.exec(b[g])||[];m=j[1];n=(j[2]||"").split(".").sort();u=q.event.r[m]||{};m=(f?u.qa:u.cb)||m;u=q.event.r[m]||{};j=q.extend({type:m,
wa:j[1],data:d,I:c,i:c.i,j:f,rc:f&&ac(f),C:n.join(".")},t);s=h[m];if(!s){s=h[m]=[];s.gb=0;if(!u.ia||u.ia.call(a,d,n,i)===l)a.addEventListener?a.addEventListener(m,i,l):a.attachEvent&&a.attachEvent("on"+m,i)}if(u.add){u.add.call(a,j);if(!j.I.i)j.I.i=c.i}f?s.splice(s.gb++,0,j):s.push(j);q.event.global[m]=e}a=k}},global:{},remove:function(a,b,c,d,f){var g=q.Xb(a)&&q.c(a),i,h,j,m,n,t,s,u,z,C;if(g&&(s=g.B)){b=q.trim(bc(b||"")).split(" ");for(i=0;i<b.length;i++){h=Vb.exec(b[i])||[];j=m=h[1];h=h[2];if(j){u=
q.event.r[j]||{};j=(d?u.qa:u.cb)||j;z=s[j]||[];n=z.length;h=h?RegExp("(^|\\.)"+h.split(".").sort().join("\\.(?:.*\\.)?")+"(\\.|$)"):k;for(t=0;t<z.length;t++){C=z[t];if((f||m===C.wa)&&(!c||c.i===C.i)&&(!h||h.test(C.C))&&(!d||d===C.j||d==="**"&&C.j)){z.splice(t--,1);C.j&&z.gb--;u.remove&&u.remove.call(a,C)}}if(z.length===0&&n!==z.length){(!u.ya||u.ya.call(a,h)===l)&&q.uc(a,j,g.handle);delete s[j]}}else for(j in s)q.event.remove(a,j+b[i],c,d,e)}if(q.La(s)){if(b=g.handle)b.f=k;q.u(a,["events","handle"],
e)}}},bd:{getData:e,setData:e,changeData:e},m:function(a,b,c,d){if(!c||!(c.nodeType===3||c.nodeType===8)){var f=a.type||a,g=[],i,h,j,m,n;if(!Zb.test(f+q.event.Bb)){if(f.indexOf("!")>=0){f=f.slice(0,-1);i=e}if(f.indexOf(".")>=0){g=f.split(".");f=g.shift();g.sort()}if(c&&!q.event.bd[f]||q.event.global[f]){a=typeof a==="object"?a[q.expando]?a:new q.K(f,a):new q.K(f);a.type=f;a.Na=e;a.hd=i;a.C=g.join(".");a.dc=a.C?RegExp("(^|\\.)"+g.join("\\.(?:.*\\.)?")+"(\\.|$)"):k;i=f.indexOf(":")<0?"on"+f:"";if(c){a.result=
p;if(!a.target)a.target=c;b=b!=k?q.T(b):[];b.unshift(a);j=q.event.r[f]||{};if(!(j.m&&j.m.apply(c,b)===l)){n=[[c,j.cb||f]];if(!d&&!j.Ed&&!q.S(c)){m=j.qa||f;g=Zb.test(m+f)?c:c.parentNode;for(h=k;g;g=g.parentNode){n.push([g,m]);h=g}h&&h===c.ownerDocument&&n.push([h.defaultView||h.parentaMaurer||o,m])}for(h=0;h<n.length&&!a.ob();h++){g=n[h][0];a.type=n[h][1];(m=(q.c(g,"events")||{})[a.type]&&q.c(g,"handle"))&&m.apply(g,b);(m=i&&g[i])&&(q.Da(g)&&m.apply(g,b)===l)&&a.preventDefault()}a.type=f;if(!d&&!a.Ka()&&
(!j.F||j.F.apply(c.ownerDocument,b)===l)&&!(f==="click"&&q.nodeName(c,"a"))&&q.Da(c))if(i&&c[f]&&(f!=="focus"&&f!=="blur"||a.target.offsetWidth!==0)&&!q.S(c)){(h=c[i])&&(c[i]=k);q.event.Bb=f;c[f]();q.event.Bb=p;h&&(c[i]=h)}return a.result}}else{c=q.G;for(h in c)c[h].B&&c[h].B[f]&&q.event.m(a,b,c[h].handle.f,e)}}}}},hb:function(a){var a=q.event.Tb(a||o.event),b=(q.c(this,"events")||{})[a.type]||[],c=b.gb,d=[].slice.call(arguments,0),f=!a.hd&&!a.C,g=q.event.r[a.type]||{},i=[],h,j,m,n,t,s,u;d[0]=a;a.dd=
this;if(!(g.Ld&&g.Ld.call(this,a)===l)){if(c&&!(a.button&&a.type==="click")){m=q(this);m.o=this.ownerDocument||this;for(j=a.target;j!=this;j=j.parentNode||this)if(j.disabled!==e){t={};s=[];m[0]=j;for(h=0;h<c;h++){n=b[h];u=n.j;if(t[u]===p){var z=t,C=u,B;if(n.rc){B=n.rc;var F=j.attributes||{};B=(!B[1]||j.nodeName.toLowerCase()===B[1])&&(!B[2]||(F.id||{}).value===B[2])&&(!B[3]||B[3].test((F["class"]||{}).value))}else B=m.ta(u);z[C]=B}t[u]&&s.push(n)}s.length&&i.push({f:j,matches:s})}}b.length>c&&i.push({f:this,
matches:b.slice(c)});for(h=0;h<i.length&&!a.ob();h++){c=i[h];a.currentTarget=c.f;for(b=0;b<c.matches.length&&!a.wd();b++){n=c.matches[b];if(f||!a.C&&!n.C||a.dc&&a.dc.test(n.C)){a.data=n.data;a.Ja=n;n=((q.event.r[n.wa]||{}).handle||n.I).apply(c.f,d);if(n!==p){a.result=n;if(n===l){a.preventDefault();a.stopPropagation()}}}}}g.nc&&g.nc.call(this,a);return a.result}},ga:"attrChange attrName relatedNode srcElement altKey bubbles cancelable ctrlKey currentTarget eventPhase metaKey relatedTarget shiftKey target timeStamp view which".split(" "),
kb:{},zd:{ga:["char","charCode","key","keyCode"],filter:function(a,b){if(a.which==k)a.which=b.charCode!=k?b.charCode:b.keyCode;return a}},Bd:{ga:"button buttons clientX clientY fromElement offsetX offsetY pageX pageY screenX screenY toElement".split(" "),filter:function(a,b){var c,d,f=b.button,g=b.fromElement;if(a.pageX==k&&b.clientX!=k){c=a.target.ownerDocument||y;d=c.documentElement;c=c.body;a.pageX=b.clientX+(d&&d.scrollLeft||c&&c.scrollLeft||0)-(d&&d.clientLeft||c&&c.clientLeft||0);a.pageY=b.clientY+
(d&&d.scrollTop||c&&c.scrollTop||0)-(d&&d.clientTop||c&&c.clientTop||0)}if(!a.relatedTarget&&g)a.relatedTarget=g===a.target?b.toElement:g;if(!a.which&&f!==p)a.which=f&1?1:f&2?3:f&4?2:0;return a}},Tb:function(a){if(a[q.expando])return a;var b,c,d=a,f=q.event.kb[a.type]||{},g=f.ga?this.ga.concat(f.ga):this.ga,a=q.K(d);for(b=g.length;b;){c=g[--b];a[c]=d[c]}if(!a.target)a.target=d.srcElement||y;if(a.target.nodeType===3)a.target=a.target.parentNode;if(a.metaKey===p)a.metaKey=a.ctrlKey;return f.filter?
f.filter(a,d):a},r:{s:{ia:q.Mb},load:{Ed:e},focus:{qa:"focusin"},blur:{qa:"focusout"},se:{ia:function(a,b,c){if(q.S(this))this.onbeforeunload=c},ya:function(a,b){if(this.onbeforeunload===b)this.onbeforeunload=k}}},Va:function(a,b,c,d){a=q.extend(new q.K,c,{type:a,ac:e,Ra:{}});d?q.event.m(a,k,b):q.event.hb.call(b,a);a.Ka()&&c.preventDefault()}};q.event.handle=q.event.hb;
q.uc=y.removeEventListener?function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c,l)}:function(a,b,c){a.detachEvent&&a.detachEvent("on"+b,c)};q.K=function(a,b){if(!(this instanceof q.K))return new q.K(a,b);if(a&&a.type){this.Ra=a;this.type=a.type;this.Ka=a.defaultPrevented||a.returnValue===l||a.md&&a.md()?fa:r}else this.type=a;b&&q.extend(this,b);this.timeStamp=a&&a.timeStamp||q.now();this[q.expando]=e};
q.K.prototype={preventDefault:function(){this.Ka=fa;var a=this.Ra;if(a)a.preventDefault?a.preventDefault():a.returnValue=l},stopPropagation:function(){this.ob=fa;var a=this.Ra;if(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=e}},Ka:r,ob:r,wd:r};q.a({Cd:"mouseover",Dd:"mouseout"},function(a,b){q.event.r[a]={qa:b,cb:b,handle:function(a){var d=a.relatedTarget,f=a.Ja,g;if(!d||d!==this&&!q.contains(this,d)){a.type=f.wa;g=f.I.apply(this,arguments);a.type=b}return g}}});
q.b.ae||(q.event.r.submit={ia:function(){if(q.nodeName(this,"form"))return l;q.event.add(this,"click._submit keypress._submit",function(a){a=a.target;if((a=q.nodeName(a,"input")||q.nodeName(a,"button")?a.form:p)&&!a.Mc){q.event.add(a,"submit._submit",function(a){a.Hb=e});a.Mc=e}})},nc:function(a){if(a.Hb){delete a.Hb;this.parentNode&&!a.Na&&q.event.Va("submit",this.parentNode,a,e)}},ya:function(){if(q.nodeName(this,"form"))return l;q.event.remove(this,"._submit")}});
q.b.Xc||(q.event.r.Wc={ia:function(){if(Ub.test(this.nodeName)){if(this.type==="checkbox"||this.type==="radio"){q.event.add(this,"propertychange._change",function(a){if(a.Ra.propertyName==="checked")this.Gb=e});q.event.add(this,"click._change",function(a){if(this.Gb&&!a.Na){this.Gb=l;q.event.Va("change",this,a,e)}})}return l}q.event.add(this,"beforeactivate._change",function(a){a=a.target;if(Ub.test(a.nodeName)&&!a.Kc){q.event.add(a,"change._change",function(a){this.parentNode&&(!a.ac&&!a.Na)&&q.event.Va("change",
this.parentNode,a,e)});a.Kc=e}})},handle:function(a){var b=a.target;if(this!==b||a.ac||a.Na||b.type!=="radio"&&b.type!=="checkbox")return a.Ja.I.apply(this,arguments)},ya:function(){q.event.remove(this,"._change");return Ub.test(this.nodeName)}});q.b.ld||q.a({focus:"focusin",blur:"focusout"},function(a,b){function c(a){q.event.Va(b,a.target,q.event.Tb(a),e)}var d=0;q.event.r[b]={ia:function(){d++===0&&y.addEventListener(a,c,e)},ya:function(){--d===0&&y.removeEventListener(a,c,e)}}});
q.d.extend({U:function(a,b,c,d,f){var g,i;if(typeof a==="object"){if(typeof b!=="string"){c=c||b;b=p}for(i in a)this.U(i,b,c,a[i],f);return this}if(c==k&&d==k){d=b;c=b=p}else if(d==k)if(typeof b==="string"){d=c;c=p}else{d=c;c=b;b=p}if(d===l)d=r;else if(!d)return this;if(f===1){g=d;d=function(a){q().D(a);return g.apply(this,arguments)};d.i=g.i||(g.i=q.i++)}return this.a(function(){q.event.add(this,a,d,c,b)})},hf:function(a,b,c,d){return this.U(a,b,c,d,1)},D:function(a,b,c){if(a&&a.preventDefault&&
a.Ja){var d=a.Ja;q(a.dd).D(d.C?d.wa+"."+d.C:d.wa,d.j,d.I);return this}if(typeof a==="object"){for(d in a)this.D(d,b,a[d]);return this}if(b===l||typeof b==="function"){c=b;b=p}c===l&&(c=r);return this.a(function(){q.event.remove(this,a,c,b)})},bind:function(a,b,c){return this.U(a,k,b,c)},Kf:function(a,b){return this.D(a,k,b)},Ye:function(a,b,c){q(this.o).U(a,this.j,b,c);return this},Ee:function(a,b){q(this.o).D(a,this.j||"**",b);return this},De:function(a,b,c,d){return this.U(b,a,c,d)},Lf:function(a,
b,c){return arguments.length==1?this.D(a,"**"):this.D(b,a,c)},m:function(a,b){return this.a(function(){q.event.m(a,b,this)})},Ab:function(a,b){if(this[0])return q.event.m(a,b,this[0],e)},toggle:function(a){function b(b){var d=(q.c(this,"lastToggle"+a.i)||0)%f;q.c(this,"lastToggle"+a.i,d+1);b.preventDefault();return c[d].apply(this,arguments)||l}var c=arguments,d=a.i||q.i++,f=0;for(b.i=d;f<c.length;)c[f++].i=d;return this.click(b)},rd:function(a,b){return this.Cd(a).Dd(b||a)}});
q.a("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error contextmenu".split(" "),function(a,b){q.d[b]=function(a,d){if(d==k){d=a;a=k}return arguments.length>0?this.U(b,k,a,d):this.m(b)};q.$a&&(q.$a[b]=e);if(Xb.test(b))q.event.kb[b]=q.event.zd;if(Yb.test(b))q.event.kb[b]=q.event.Bd});
function cc(a,b,c,d,f,g){for(var f=0,i=d.length;f<i;f++){var h=d[f];if(h){for(var j=l,h=h[a];h;){if(h[dc]===c){j=d[h.yb];break}if(h.nodeType===1&&!g){h[dc]=c;h.yb=f}if(h.nodeName.toLowerCase()===b){j=h;break}h=h[a]}d[f]=j}}}function ec(a,b,c,d,f,g){for(var f=0,i=d.length;f<i;f++){var h=d[f];if(h){for(var j=l,h=h[a];h;){if(h[dc]===c){j=d[h.yb];break}if(h.nodeType===1){if(!g){h[dc]=c;h.yb=f}if(typeof b!=="string"){if(h===b){j=e;break}}else if(T.filter(b,[h]).length>0){j=h;break}}h=h[a]}d[f]=j}}}
var fc=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^\[\]]*\]|['"][^'"]*['"]|[^\[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,dc="sizcache"+(Math.random()+"").replace(".",""),gc=0,hc=Object.prototype.toString,ic=l,jc=e,kc=/\\/g,lc=/\r\n/g,mc=/\W/;[0,0].sort(function(){jc=l;return 0});
function T(a,b,c,d){var c=c||[],f=b=b||y;if(b.nodeType!==1&&b.nodeType!==9)return[];if(!a||typeof a!=="string")return c;var g,i,h,j,m,n=e,t=T.ua(b),s=[],u=a;do{fc.exec("");if(g=fc.exec(u)){u=g[3];s.push(g[1]);if(g[2]){j=g[3];break}}}while(g);if(s.length>1&&nc.exec(a))if(s.length===2&&U.ha[s[0]])i=oc(s[0]+s[1],b,d);else for(i=U.ha[s[0]]?[b]:T(s.shift(),b);s.length;){a=s.shift();U.ha[a]&&(a=a+s.shift());i=oc(a,i,d)}else{if(!d&&s.length>1&&b.nodeType===9&&!t&&U.match.L.test(s[0])&&!U.match.L.test(s[s.length-
1])){g=T.find(s.shift(),b,t);b=g.l?T.filter(g.l,g.set)[0]:g.set[0]}if(b){g=d?{l:s.pop(),set:V(d)}:T.find(s.pop(),s.length===1&&(s[0]==="~"||s[0]==="+")&&b.parentNode?b.parentNode:b,t);i=g.l?T.filter(g.l,g.set):g.set;for(s.length>0?h=V(i):n=l;s.length;){g=m=s.pop();U.ha[m]?g=s.pop():m="";g==k&&(g=b);U.ha[m](h,g,t)}}else h=[]}h||(h=i);h||T.error(m||a);if(hc.call(h)==="[object Array]")if(n)if(b&&b.nodeType===1)for(a=0;h[a]!=k;a++)h[a]&&(h[a]===e||h[a].nodeType===1&&T.contains(b,h[a]))&&c.push(i[a]);
else for(a=0;h[a]!=k;a++)h[a]&&h[a].nodeType===1&&c.push(i[a]);else c.push.apply(c,h);else V(h,c);if(j){T(j,f,c,d);T.Gc(c)}return c}T.Gc=function(a){if(pc){ic=jc;a.sort(pc);if(ic)for(var b=1;b<a.length;b++)a[b]===a[b-1]&&a.splice(b--,1)}return a};T.matches=function(a,b){return T(a,k,k,b)};T.matchesSelector=function(a,b){return T(b,k,k,[a]).length>0};
T.find=function(a,b,c){var d,f,g,i,h,j;if(!a)return[];f=0;for(g=U.ub.length;f<g;f++){h=U.ub[f];if(i=U.rb[h].exec(a)){j=i[1];i.splice(1,1);if(j.substr(j.length-1)!=="\\"){i[1]=(i[1]||"").replace(kc,"");d=U.find[h](i,b,c);if(d!=k){a=a.replace(U.match[h],"");break}}}}d||(d=typeof b.getElementsByTagName!=="undefined"?b.getElementsByTagName("*"):[]);return{set:d,l:a}};
T.filter=function(a,b,c,d){for(var f,g,i,h,j,m,n,t,s=a,u=[],z=b,C=b&&b[0]&&T.ua(b[0]);a&&b.length;){for(i in U.filter)if((f=U.rb[i].exec(a))!=k&&f[2]){m=U.filter[i];j=f[1];g=l;f.splice(1,1);if(j.substr(j.length-1)!=="\\"){z===u&&(u=[]);if(U.oc[i])if(f=U.oc[i](f,z,c,u,d,C)){if(f===e)continue}else g=h=e;if(f)for(n=0;(j=z[n])!=k;n++)if(j){h=m(j,f,n,z);t=d^h;if(c&&h!=k)t?g=e:z[n]=l;else if(t){u.push(j);g=e}}if(h!==p){c||(z=u);a=a.replace(U.match[i],"");if(!g)return[];break}}}if(a===s)if(g==k)T.error(a);
else break;s=a}return z};T.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};
var qc=T.od=function(a){var b,c;b=a.nodeType;var d="";if(b)if(b===1||b===9||b===11){if(typeof a.textContent==="string")return a.textContent;if(typeof a.innerText==="string")return a.innerText.replace(lc,"");for(a=a.firstChild;a;a=a.nextSibling)d=d+qc(a)}else{if(b===3||b===4)return a.nodeValue}else for(b=0;c=a[b];b++)c.nodeType!==8&&(d=d+qc(c));return d},U=T.wc={ub:["ID","NAME","TAG"],match:{L:/#((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,za:/\.((?:[\w\u00c0-\uFFFF\-]|\\.)+)/,Jc:/\[name=['"]*((?:[\w\u00c0-\uFFFF\-]|\\.)+)['"]*\]/,
Fb:/\[\s*((?:[\w\u00c0-\uFFFF\-]|\\.)+)\s*(?:(\S?=)\s*(?:(['"])(.*?)\3|(#?(?:[\w\u00c0-\uFFFF\-]|\\.)*)|)|)\s*\]/,Ca:/^((?:[\w\u00c0-\uFFFF\*\-]|\\.)+)/,Ya:/:(only|nth|last|first)-child(?:\(\s*(even|odd|(?:[+\-]?\d+|(?:[+\-]?\d*)?n\s*(?:[+\-]\s*\d+)?))\s*\))?/,Ba:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^\-]|$)/,ja:/:((?:[\w\u00c0-\uFFFF\-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},rb:{},bb:{"class":"className","for":"htmlFor"},ab:{href:function(a){return a.getAttribute("href")},
type:function(a){return a.getAttribute("type")}},ha:{"+":function(a,b){var c=typeof b==="string",d=c&&!mc.test(b),c=c&&!d;d&&(b=b.toLowerCase());for(var d=0,f=a.length,g;d<f;d++)if(g=a[d]){for(;(g=g.previousSibling)&&g.nodeType!==1;);a[d]=c||g&&g.nodeName.toLowerCase()===b?g||l:g===b}c&&T.filter(b,a,e)},">":function(a,b){var c,d=typeof b==="string",f=0,g=a.length;if(d&&!mc.test(b))for(b=b.toLowerCase();f<g;f++){if(c=a[f]){c=c.parentNode;a[f]=c.nodeName.toLowerCase()===b?c:l}}else{for(;f<g;f++)(c=
a[f])&&(a[f]=d?c.parentNode:c.parentNode===b);d&&T.filter(b,a,e)}},"":function(a,b,c){var d,f=gc++,g=ec;if(typeof b==="string"&&!mc.test(b)){d=b=b.toLowerCase();g=cc}g("parentNode",b,f,a,d,c)},"~":function(a,b,c){var d,f=gc++,g=ec;if(typeof b==="string"&&!mc.test(b)){d=b=b.toLowerCase();g=cc}g("previousSibling",b,f,a,d,c)}},find:{L:function(a,b,c){if(typeof b.getElementById!=="undefined"&&!c)return(a=b.getElementById(a[1]))&&a.parentNode?[a]:[]},Jc:function(a,b){if(typeof b.getElementsByName!=="undefined"){for(var c=
[],d=b.getElementsByName(a[1]),f=0,g=d.length;f<g;f++)d[f].getAttribute("name")===a[1]&&c.push(d[f]);return c.length===0?k:c}},Ca:function(a,b){if(typeof b.getElementsByTagName!=="undefined")return b.getElementsByTagName(a[1])}},oc:{za:function(a,b,c,d,f,g){a=" "+a[1].replace(kc,"")+" ";if(g)return a;for(var g=0,i;(i=b[g])!=k;g++)i&&(f^(i.className&&(" "+i.className+" ").replace(/[\t\n\r]/g," ").indexOf(a)>=0)?c||d.push(i):c&&(b[g]=l));return l},L:function(a){return a[1].replace(kc,"")},Ca:function(a){return a[1].replace(kc,
"").toLowerCase()},Ya:function(a){if(a[1]==="nth"){a[2]||T.error(a[0]);a[2]=a[2].replace(/^\+|\s*/g,"");var b=/(-?)(\d*)(?:n([+\-]?\d*))?/.exec(a[2]==="even"&&"2n"||a[2]==="odd"&&"2n+1"||!/\D/.test(a[2])&&"0n+"+a[2]||a[2]);a[2]=b[1]+(b[2]||1)-0;a[3]=b[3]-0}else a[2]&&T.error(a[0]);a[0]=gc++;return a},Fb:function(a,b,c,d,f,g){b=a[1]=a[1].replace(kc,"");!g&&U.bb[b]&&(a[1]=U.bb[b]);a[4]=(a[4]||a[5]||"").replace(kc,"");a[2]==="~="&&(a[4]=" "+a[4]+" ");return a},ja:function(a,b,c,d,f){if(a[1]==="not")if((fc.exec(a[3])||
"").length>1||/^\w/.test(a[3]))a[3]=T(a[3],k,k,b);else{a=T.filter(a[3],b,c,1^f);c||d.push.apply(d,a);return l}else if(U.match.Ba.test(a[0])||U.match.Ya.test(a[0]))return e;return a},Ba:function(a){a.unshift(e);return a}},H:{enabled:function(a){return a.disabled===l&&a.type!=="hidden"},disabled:function(a){return a.disabled===e},checked:function(a){return a.checked===e},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return a.selected===e},parent:function(a){return!!a.firstChild},empty:function(a){return!a.firstChild},
lb:function(a,b,c){return!!T(c[3],a).length},Qe:function(a){return/h\d/i.test(a.nodeName)},text:function(a){var b=a.getAttribute("type"),c=a.type;return a.nodeName.toLowerCase()==="input"&&"text"===c&&(b===c||b===k)},rf:function(a){return a.nodeName.toLowerCase()==="input"&&"radio"===a.type},ve:function(a){return a.nodeName.toLowerCase()==="input"&&"checkbox"===a.type},file:function(a){return a.nodeName.toLowerCase()==="input"&&"file"===a.type},Kd:function(a){return a.nodeName.toLowerCase()==="input"&&
"password"===a.type},submit:function(a){var b=a.nodeName.toLowerCase();return(b==="input"||b==="button")&&"submit"===a.type},Se:function(a){return a.nodeName.toLowerCase()==="input"&&"image"===a.type},reset:function(a){var b=a.nodeName.toLowerCase();return(b==="input"||b==="button")&&"reset"===a.type},button:function(a){var b=a.nodeName.toLowerCase();return b==="input"&&"button"===a.type||b==="button"},input:function(a){return/input|select|textarea|button/i.test(a.nodeName)},focus:function(a){return a===
a.ownerDocument.activeElement}},Yd:{jd:function(a,b){return b===0},Ad:function(a,b,c,d){return b===d.length-1},Fe:function(a,b){return b%2===0},gf:function(a,b){return b%2===1},$e:function(a,b,c){return b<c[3]-0},Pe:function(a,b,c){return b>c[3]-0},tb:function(a,b,c){return c[3]-0===b},Ha:function(a,b,c){return c[3]-0===b}},filter:{ja:function(a,b,c,d){var f=b[1],g=U.H[f];if(g)return g(a,c,b,d);if(f==="contains")return(a.textContent||a.innerText||qc([a])||"").indexOf(b[3])>=0;if(f==="not"){b=b[3];
c=0;for(d=b.length;c<d;c++)if(b[c]===a)return l;return e}T.error(f)},Ya:function(a,b){var c,d,f,g,i,h;c=b[1];h=a;switch(c){case "only":case "first":for(;h=h.previousSibling;)if(h.nodeType===1)return l;if(c==="first")return e;h=a;case "last":for(;h=h.nextSibling;)if(h.nodeType===1)return l;return e;case "nth":c=b[2];d=b[3];if(c===1&&d===0)return e;f=b[0];if((g=a.parentNode)&&(g[dc]!==f||!a.gc)){i=0;for(h=g.firstChild;h;h=h.nextSibling)if(h.nodeType===1)h.gc=++i;g[dc]=f}h=a.gc-d;return c===0?h===0:
h%c===0&&h/c>=0}},L:function(a,b){return a.nodeType===1&&a.getAttribute("id")===b},Ca:function(a,b){return b==="*"&&a.nodeType===1||!!a.nodeName&&a.nodeName.toLowerCase()===b},za:function(a,b){return(" "+(a.className||a.getAttribute("class"))+" ").indexOf(b)>-1},Fb:function(a,b){var c=b[1],c=T.z?T.z(a,c):U.ab[c]?U.ab[c](a):a[c]!=k?a[c]:a.getAttribute(c),d=c+"",f=b[2],g=b[4];return c==k?f==="!=":!f&&T.z?c!=k:f==="="?d===g:f==="*="?d.indexOf(g)>=0:f==="~="?(" "+d+" ").indexOf(g)>=0:!g?d&&c!==l:f===
"!="?d!==g:f==="^="?d.indexOf(g)===0:f==="$="?d.substr(d.length-g.length)===g:f==="|="?d===g||d.substr(0,g.length+1)===g+"-":l},Ba:function(a,b,c,d){var f=U.Yd[b[2]];if(f)return f(a,c,b,d)}}},nc=U.match.Ba;function rc(a,b){return"\\"+(b-0+1)}for(var sc in U.match)U.match[sc]=RegExp(U.match[sc].source+/(?![^\[]*\])(?![^\(]*\))/.source),U.rb[sc]=RegExp(/(^(?:.|\r|\n)*?)/.source+U.match[sc].source.replace(/\\(\d+)/g,rc));U.match.pd=nc;
function V(a,b){a=Array.prototype.slice.call(a,0);if(b){b.push.apply(b,a);return b}return a}try{Array.prototype.slice.call(y.documentElement.childNodes,0)[0].nodeType}catch(tc){V=function(a,b){var c=0,d=b||[];if(hc.call(a)==="[object Array]")Array.prototype.push.apply(d,a);else if(typeof a.length==="number")for(var f=a.length;c<f;c++)d.push(a[c]);else for(;a[c];c++)d.push(a[c]);return d}}var pc,uc;
y.documentElement.compareDocumentPosition?pc=function(a,b){if(a===b){ic=e;return 0}return!a.compareDocumentPosition||!b.compareDocumentPosition?a.compareDocumentPosition?-1:1:a.compareDocumentPosition(b)&4?-1:1}:(pc=function(a,b){if(a===b){ic=e;return 0}if(a.sourceIndex&&b.sourceIndex)return a.sourceIndex-b.sourceIndex;var c,d,f=[],g=[];c=a.parentNode;d=b.parentNode;var i=c;if(c===d)return uc(a,b);if(c){if(!d)return 1}else return-1;for(;i;){f.unshift(i);i=i.parentNode}for(i=d;i;){g.unshift(i);i=i.parentNode}c=
f.length;d=g.length;for(i=0;i<c&&i<d;i++)if(f[i]!==g[i])return uc(f[i],g[i]);return i===c?uc(a,g[i],-1):uc(f[i],b,1)},uc=function(a,b,c){if(a===b)return c;for(a=a.nextSibling;a;){if(a===b)return-1;a=a.nextSibling}return 1});var vc=y.createElement("div"),wc="script"+(new Date).getTime(),xc=y.documentElement;vc.innerHTML="<a name='"+wc+"'/>";xc.insertBefore(vc,xc.firstChild);
y.getElementById(wc)&&(U.find.L=function(a,b,c){if(typeof b.getElementById!=="undefined"&&!c)return(b=b.getElementById(a[1]))?b.id===a[1]||typeof b.getAttributeNode!=="undefined"&&b.getAttributeNode("id").nodeValue===a[1]?[b]:p:[]},U.filter.L=function(a,b){var c=typeof a.getAttributeNode!=="undefined"&&a.getAttributeNode("id");return a.nodeType===1&&c&&c.nodeValue===b});xc.removeChild(vc);var xc=vc=k,X=y.createElement("div");X.appendChild(y.createComment(""));
0<X.getElementsByTagName("*").length&&(U.find.Ca=function(a,b){var c=b.getElementsByTagName(a[1]);if(a[1]==="*"){for(var d=[],f=0;c[f];f++)c[f].nodeType===1&&d.push(c[f]);c=d}return c});X.innerHTML="<a href='#'></a>";X.firstChild&&("undefined"!==typeof X.firstChild.getAttribute&&"#"!==X.firstChild.getAttribute("href"))&&(U.ab.href=function(a){return a.getAttribute("href",2)});X=k;
if(y.querySelectorAll){var yc=T,zc=y.createElement("div");zc.innerHTML="<p class='TEST'></p>";if(!(zc.querySelectorAll&&0===zc.querySelectorAll(".TEST").length)){var T=function(a,b,c,d){b=b||y;if(!d&&!T.ua(b)){var f=/^(\w+$)|^\.([\w\-]+$)|^#([\w\-]+$)/.exec(a);if(f&&(b.nodeType===1||b.nodeType===9)){if(f[1])return V(b.getElementsByTagName(a),c);if(f[2]&&U.find.za&&b.getElementsByClassName)return V(b.getElementsByClassName(f[2]),c)}if(b.nodeType===9){if(a==="body"&&b.body)return V([b.body],c);if(f&&
f[3]){var g=b.getElementById(f[3]);if(g&&g.parentNode){if(g.id===f[3])return V([g],c)}else return V([],c)}try{return V(b.querySelectorAll(a),c)}catch(i){}}else if(b.nodeType===1&&b.nodeName.toLowerCase()!=="object"){var f=b,h=(g=b.getAttribute("id"))||"__sizzle__",j=b.parentNode,m=/^\s*[+~]/.test(a);g?h=h.replace(/'/g,"\\$&"):b.setAttribute("id",h);if(m&&j)b=b.parentNode;try{if(!m||j)return V(b.querySelectorAll("[id='"+h+"'] "+a),c)}catch(n){}finally{g||f.removeAttribute("id")}}}return yc(a,b,c,d)},
Ac;for(Ac in yc)T[Ac]=yc[Ac];zc=k}}var Bc=y.documentElement,Cc=Bc.matchesSelector||Bc.mozMatchesSelector||Bc.webkitMatchesSelector||Bc.msMatchesSelector;
if(Cc){var Dc=!Cc.call(y.createElement("div"),"div"),Ec=l;try{Cc.call(y.documentElement,"[test!='']:sizzle")}catch(Fc){Ec=e}T.matchesSelector=function(a,b){b=b.replace(/\=\s*([^'"\]]*)\s*\]/g,"='$1']");if(!T.ua(a))try{if(Ec||!U.match.ja.test(b)&&!/!=/.test(b)){var c=Cc.call(a,b);if(c||!Dc||a.document&&a.document.nodeType!==11)return c}}catch(d){}return T(b,k,k,[a]).length>0}}var Gc=y.createElement("div");Gc.innerHTML="<div class='test e'></div><div class='test'></div>";
Gc.getElementsByClassName&&0!==Gc.getElementsByClassName("e").length&&(Gc.lastChild.className="e",1!==Gc.getElementsByClassName("e").length&&(U.ub.splice(1,0,"CLASS"),U.find.za=function(a,b,c){if(typeof b.getElementsByClassName!=="undefined"&&!c)return b.getElementsByClassName(a[1])},Gc=k));T.contains=y.documentElement.contains?function(a,b){return a!==b&&(a.contains?a.contains(b):e)}:y.documentElement.compareDocumentPosition?function(a,b){return!!(a.compareDocumentPosition(b)&16)}:function(){return l};
T.ua=function(a){return(a=(a?a.ownerDocument||a:0).documentElement)?a.nodeName!=="HTML":l};function oc(a,b,c){for(var d,f=[],g="",b=b.nodeType?[b]:b;d=U.match.ja.exec(a);){g=g+d[0];a=a.replace(U.match.ja,"")}a=U.ha[a]?a+"*":a;d=0;for(var i=b.length;d<i;d++)T(a,b[d],f,c);return T.filter(g,f)}T.z=q.z;T.wc.bb={};q.find=T;q.l=T.wc;q.l[":"]=q.l.H;q.unique=T.Gc;q.text=T.od;q.Oa=T.ua;q.contains=T.contains;
var Hc=/Until$/,Ic=/^(?:parents|prevUntil|prevAll)/,Jc=/,/,ja=/^.[^:#\[\.,]*$/,Kc=Array.prototype.slice,Lc=q.l.match.pd,Mc={children:e,ma:e,next:e,Md:e};
q.d.extend({find:function(a){var b=this,c,d;if(typeof a!=="string")return q(a).filter(function(){c=0;for(d=b.length;c<d;c++)if(q.contains(b[c],this))return e});var f=this.q("","find",a),g,i,h;c=0;for(d=this.length;c<d;c++){g=f.length;q.find(a,this[c],f);if(c>0)for(i=g;i<f.length;i++)for(h=0;h<g;h++)if(f[h]===f[i]){f.splice(i--,1);break}}return f},lb:function(a){var b=q(a);return this.filter(function(){for(var a=0,d=b.length;a<d;a++)if(q.contains(this,b[a]))return e})},ef:function(a){return this.q(ia(this,
a,l),"not",a)},filter:function(a){return this.q(ia(this,a,e),"filter",a)},ta:function(a){return!!a&&(typeof a==="string"?Lc.test(a)?q(a,this.o).index(this[0])>=0:q.filter(a,this).length>0:this.filter(a).length>0)},xe:function(a,b){var c=[],d,f,g=this[0];if(q.isArray(a)){for(f=1;g&&g.ownerDocument&&g!==b;){for(d=0;d<a.length;d++)q(g).ta(a[d])&&c.push({j:a[d],f:g,We:f});g=g.parentNode;f++}return c}var i=Lc.test(a)||typeof a!=="string"?q(a,b||this.o):0;d=0;for(f=this.length;d<f;d++)for(g=this[d];g;)if(i?
i.index(g)>-1:q.find.matchesSelector(g,a)){c.push(g);break}else{g=g.parentNode;if(!g||!g.ownerDocument||g===b||g.nodeType===11)break}c=c.length>1?q.unique(c):c;return this.q(c,"closest",a)},index:function(a){return!a?this[0]&&this[0].parentNode?this.Nd().length:-1:typeof a==="string"?q.ea(this[0],q(a)):q.ea(a.v?a[0]:a,this)},add:function(a,b){var c=typeof a==="string"?q(a,b):q.T(a&&a.nodeType?[a]:a),d=q.va(this.get(),c);return this.q(!c[0]||!c[0].parentNode||c[0].parentNode.nodeType===11||!d[0]||
!d[0].parentNode||d[0].parentNode.nodeType===11?d:q.unique(d))},pe:function(){return this.add(this.pc)}});
q.a({parent:function(a){return(a=a.parentNode)&&a.nodeType!==11?a:k},kf:function(a){return q.dir(a,"parentNode")},lf:function(a,b,c){return q.dir(a,"parentNode",c)},next:function(a){return q.tb(a,2,"nextSibling")},Md:function(a){return q.tb(a,2,"previousSibling")},bf:function(a){return q.dir(a,"nextSibling")},Nd:function(a){return q.dir(a,"previousSibling")},cf:function(a,b,c){return q.dir(a,"nextSibling",c)},pf:function(a,b,c){return q.dir(a,"previousSibling",c)},zf:function(a){return q.yc((a.parentNode||
{}).firstChild,a)},children:function(a){return q.yc(a.firstChild)},ma:function(a){return q.nodeName(a,"iframe")?a.contentDocument||a.contentaMaurer.document:q.T(a.childNodes)}},function(a,b){q.d[a]=function(c,d){var f=q.map(this,b,c);Hc.test(a)||(d=c);d&&typeof d==="string"&&(f=q.filter(d,f));f=this.length>1&&!Mc[a]?q.unique(f):f;if((this.length>1||Jc.test(d))&&Ic.test(a))f=f.reverse();return this.q(f,a,Kc.call(arguments).join(","))}});
q.extend({filter:function(a,b,c){c&&(a=":not("+a+")");return b.length===1?q.find.matchesSelector(b[0],a)?[b[0]]:[]:q.find.matches(a,b)},dir:function(a,b,c){for(var d=[],a=a[b];a&&a.nodeType!==9&&(c===p||a.nodeType!==1||!q(a).ta(c));){a.nodeType===1&&d.push(a);a=a[b]}return d},tb:function(a,b,c){for(var b=b||1,d=0;a;a=a[c])if(a.nodeType===1&&++d===b)break;return a},yc:function(a,b){for(var c=[];a;a=a.nextSibling)a.nodeType===1&&a!==b&&c.push(a);return c}});
var ma="abbr|article|aside|audio|bdi|canvas|data|datalist|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video",Nc=/ aQuery\d+="(?:\d+|null)"/g,Oc=/^\s+/,Pc=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,Qc=/<([\w:]+)/,Rc=/<tbody/i,Sc=/<|&#?\w+;/,Tc=/<(?:script|style)/i,Uc=/<(?:script|object|embed|option|style)/i,Vc=RegExp("<(?:"+ma+")[\\s/>]","i"),Wc=/checked\s*(?:[^=]|=\s*.checked.)/i,Xc=/\/(java|ecma)script/i,Yc=/^\s*<!(?:\[CDATA\[|\-\-)/,
Y={kc:[1,"<select multiple='multiple'>","</select>"],Ve:[1,"<fieldset>","</fieldset>"],de:[1,"<table>","</table>"],Jf:[2,"<table><tbody>","</tbody></table>"],ce:[3,"<table><tbody><tr>","</tr></tbody></table>"],ye:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],re:[1,"<map>","</map>"],F:[0,"",""]},Zc=la(y);Y.jf=Y.kc;Y.Dc=Y.Hf=Y.ze=Y.caption=Y.de;Y.If=Y.ce;q.b.td||(Y.F=[1,"div<div>","</div>"]);
q.d.extend({text:function(a){return q.w(this,function(a){return a===p?q.text(this):this.empty().append((this[0]&&this[0].ownerDocument||y).createTextNode(a))},k,a,arguments.length)},Db:function(a){if(q.g(a))return this.a(function(b){q(this).Db(a.call(this,b))});if(this[0]){var b=q(a,this[0].ownerDocument).Ha(0).Y(e);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var a=this;a.firstChild&&a.firstChild.nodeType===1;)a=a.firstChild;return a}).append(this)}return this},je:function(a){return q.g(a)?
this.a(function(b){q(this).je(a.call(this,b))}):this.a(function(){var b=q(this),c=b.ma();c.length?c.Db(a):b.append(a)})},Sf:function(a){var b=q.g(a);return this.a(function(c){q(this).Db(b?a.call(this,c):a)})},Nf:function(){return this.parent().a(function(){q.nodeName(this,"body")||q(this).vc(this.childNodes)}).end()},append:function(){return this.aa(arguments,e,function(a){this.nodeType===1&&this.appendChild(a)})},nf:function(){return this.aa(arguments,e,function(a){this.nodeType===1&&this.insertBefore(a,
this.firstChild)})},Tc:function(){if(this[0]&&this[0].parentNode)return this.aa(arguments,l,function(a){this.parentNode.insertBefore(a,this)});if(arguments.length){var a=q.eb(arguments);a.push.apply(a,this.Ec());return this.q(a,"before",arguments)}},oe:function(){if(this[0]&&this[0].parentNode)return this.aa(arguments,l,function(a){this.parentNode.insertBefore(a,this.nextSibling)});if(arguments.length){var a=this.q(this,"after",arguments);a.push.apply(a,q.eb(arguments));return a}},remove:function(a,
b){for(var c=0,d;(d=this[c])!=k;c++)if(!a||q.filter(a,[d]).length){if(!b&&d.nodeType===1){q.Fa(d.getElementsByTagName("*"));q.Fa([d])}d.parentNode&&d.parentNode.removeChild(d)}return this},empty:function(){for(var a=0,b;(b=this[a])!=k;a++)for(b.nodeType===1&&q.Fa(b.getElementsByTagName("*"));b.firstChild;)b.removeChild(b.firstChild);return this},Y:function(a,b){a=a==k?l:a;b=b==k?a:b;return this.map(function(){return q.Y(this,a,b)})},da:function(a){return q.w(this,function(a){var c=this[0]||{},d=0,
f=this.length;if(a===p)return c.nodeType===1?c.innerHTML.replace(Nc,""):k;if(typeof a==="string"&&!Tc.test(a)&&(q.b.bc||!Oc.test(a))&&!Y[(Qc.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(Pc,"<$1></$2>");try{for(;d<f;d++){c=this[d]||{};if(c.nodeType===1){q.Fa(c.getElementsByTagName("*"));c.innerHTML=a}}c=0}catch(g){}}c&&this.empty().append(a)},k,a,arguments.length)},vc:function(a){if(this[0]&&this[0].parentNode){if(q.g(a))return this.a(function(b){var c=q(this),d=c.da();c.vc(a.call(this,b,d))});
typeof a!=="string"&&(a=q(a).detach());return this.a(function(){var b=this.nextSibling,c=this.parentNode;q(this).remove();b?q(b).Tc(a):q(c).append(a)})}return this.length?this.q(q(q.g(a)?a():a),"replaceWith",a):this},detach:function(a){return this.remove(a,e)},aa:function(a,b,c){var d,f,g,i=a[0],h=[];if(!q.b.Pb&&arguments.length===3&&typeof i==="string"&&Wc.test(i))return this.a(function(){q(this).aa(a,b,c,e)});if(q.g(i))return this.a(function(d){var f=q(this);a[0]=i.call(this,d,b?f.da():p);f.aa(a,
b,c)});if(this[0]){d=i&&i.parentNode;d=q.b.parentNode&&d&&d.nodeType===11&&d.childNodes.length===this.length?{Ia:d}:q.Nb(a,this,h);g=d.Ia;if(f=g.childNodes.length===1?g=g.firstChild:g.firstChild){b=b&&q.nodeName(f,"tr");f=0;for(var j=this.length,m=j-1;f<j;f++)c.call(b?q.nodeName(this[f],"table")?this[f].getElementsByTagName("tbody")[0]||this[f].appendChild(this[f].ownerDocument.createElement("tbody")):this[f]:this[f],d.Ob||j>1&&f<m?q.Y(g,e,e):g)}h.length&&q.a(h,function(a,b){b.src?q.ka({type:"GET",
global:l,url:b.src,async:l,dataType:"script"}):q.Wb((b.text||b.textContent||b.innerHTML||"").replace(Yc,"/*$0*/"));b.parentNode&&b.parentNode.removeChild(b)})}return this}});
q.Nb=function(a,b,c){var d,f,g,i,h=a[0];b&&b[0]&&(i=b[0].ownerDocument||b[0]);i.createDocumentFragment||(i=y);if(a.length===1&&typeof h==="string"&&h.length<512&&i===y&&h.charAt(0)==="<"&&!Uc.test(h)&&(q.b.Pb||!Wc.test(h))&&(q.b.Yb||!Vc.test(h))){f=e;(g=q.Vb[h])&&g!==1&&(d=g)}if(!d){d=i.createDocumentFragment();q.eb(a,i,d,c)}f&&(q.Vb[h]=g?d:1);return{Ia:d,Ob:f}};q.Vb={};
q.a({Sc:"append",of:"prepend",insertBefore:"before",Te:"after",vf:"replaceWith"},function(a,b){q.d[a]=function(c){var d=[],c=q(c),f=this.length===1&&this[0].parentNode;if(f&&f.nodeType===11&&f.childNodes.length===1&&c.length===1){c[b](this[0]);return this}for(var f=0,g=c.length;f<g;f++){var i=(f>0?this.Y(e):this).get();q(c[f])[b](i);d=d.concat(i)}return this.q(d,a,c.j)}});
q.extend({Y:function(a,b,c){var d,f,g;if(q.b.Yb||q.Oa(a)||!Vc.test("<"+a.nodeName+">"))d=a.cloneNode(e);else{d=y.createElement("div");Zc.appendChild(d);d.innerHTML=a.outerHTML;d=d.firstChild}var i=d;if((!q.b.ec||!q.b.Fd)&&(a.nodeType===1||a.nodeType===11)&&!q.Oa(a)){ra(a,i);d=sa(a);f=sa(i);for(g=0;d[g];++g)f[g]&&ra(d[g],f[g])}if(b){qa(a,i);if(c){d=sa(a);f=sa(i);for(g=0;d[g];++g)qa(d[g],f[g])}}return i},eb:function(a,b,c,d){var f,g=[],b=b||y;typeof b.createElement==="undefined"&&(b=b.ownerDocument||
b[0]&&b[0].ownerDocument||y);for(var i=0,h;(h=a[i])!=k;i++){typeof h==="number"&&(h=h+"");if(h){if(typeof h==="string")if(Sc.test(h)){h=h.replace(Pc,"<$1></$2>");f=(Qc.exec(h)||["",""])[1].toLowerCase();var j=Y[f]||Y.F,m=j[0],n=b.createElement("div"),t=Zc.childNodes;b===y?Zc.appendChild(n):la(b).appendChild(n);for(n.innerHTML=j[1]+h+j[2];m--;)n=n.lastChild;if(!q.b.Dc){m=Rc.test(h);j=f==="table"&&!m?n.firstChild&&n.firstChild.childNodes:j[1]==="<table>"&&!m?n.childNodes:[];for(f=j.length-1;f>=0;--f)q.nodeName(j[f],
"tbody")&&!j[f].childNodes.length&&j[f].parentNode.removeChild(j[f])}!q.b.bc&&Oc.test(h)&&n.insertBefore(b.createTextNode(Oc.exec(h)[0]),n.firstChild);h=n.childNodes;if(n){n.parentNode.removeChild(n);if(t.length>0)(n=t[t.length-1])&&n.parentNode&&n.parentNode.removeChild(n)}}else h=b.createTextNode(h);var s;if(!q.b.Rc)if(h[0]&&typeof(s=h.length)==="number")for(f=0;f<s;f++)ua(h[f]);else ua(h);h.nodeType?g.push(h):g=q.va(g,h)}}if(c){a=function(a){return!a.type||Xc.test(a.type)};for(i=0;g[i];i++){b=
g[i];if(d&&q.nodeName(b,"script")&&(!b.type||Xc.test(b.type)))d.push(b.parentNode?b.parentNode.removeChild(b):b);else{if(b.nodeType===1){h=q.R(b.getElementsByTagName("script"),a);g.splice.apply(g,[i+1,0].concat(h))}c.appendChild(b)}}}return g},Fa:function(a){for(var b,c,d=q.G,f=q.event.r,g=q.b.Ga,i=0,h;(h=a[i])!=k;i++)if(!h.nodeName||!q.fc[h.nodeName.toLowerCase()])if(c=h[q.expando]){if((b=d[c])&&b.B){for(var j in b.B)f[j]?q.event.remove(h,j):q.uc(h,j,b.handle);if(b.handle)b.handle.f=k}g?delete h[q.expando]:
h.removeAttribute&&h.removeAttribute(q.expando);delete d[c]}}});var $c=/alpha\([^)]*\)/i,ad=/opacity=([^)]*)/,bd=/([A-Z]|^ms)/g,cd=/^[\-+]?(?:\d*\.)?\d+$/i,wa=/^-?(?:\d*\.)?\d+(?!px)[^\d\s]+$/i,dd=/^([\-+])=([\-+.\de]+)/,ed=/^margin/,fd={position:"absolute",visibility:"hidden",display:"block"},v=["Top","Right","Bottom","Left"],w,gd,hd;q.d.e=function(a,b){return q.w(this,function(a,b,f){return f!==p?q.style(a,b,f):q.e(a,b)},a,b,arguments.length>1)};
q.extend({Q:{opacity:{get:function(a,b){if(b){var c=w(a,"opacity");return c===""?"1":c}return a.style.opacity}}},fb:{fillOpacity:e,fontWeight:e,lineHeight:e,opacity:e,orphans:e,widows:e,zIndex:e,zoom:e},Qb:{"float":q.b.cssFloat?"cssFloat":"styleFloat"},style:function(a,b,c,d){if(a&&!(a.nodeType===3||a.nodeType===8||!a.style)){var f,g=q.P(b),i=a.style,h=q.Q[g],b=q.Qb[g]||g;if(c!==p){d=typeof c;if(d==="string"&&(f=dd.exec(c))){c=+(f[1]+1)*+f[2]+parseFloat(q.e(a,b));d="number"}if(!(c==k||d==="number"&&
isNaN(c))){d==="number"&&!q.fb[g]&&(c=c+"px");if(!h||!("set"in h)||(c=h.set(a,c))!==p)try{i[b]=c}catch(j){}}}else return h&&"get"in h&&(f=h.get(a,l,d))!==p?f:i[b]}},e:function(a,b,c){var d,f,b=q.P(b);f=q.Q[b];b=q.Qb[b]||b;b==="cssFloat"&&(b="float");if(f&&"get"in f&&(d=f.get(a,e,c))!==p)return d;if(w)return w(a,b)},Bc:function(a,b,c){var d={},f;for(f in b){d[f]=a.style[f];a.style[f]=b[f]}c=c.call(a);for(f in b)a.style[f]=d[f];return c}});q.Be=q.e;
y.defaultView&&y.defaultView.getComputedStyle&&(gd=function(a,b){var c,d,f,g=a.style,b=b.replace(bd,"-$1").toLowerCase();if((d=a.ownerDocument.defaultView)&&(f=d.getComputedStyle(a,k))){c=f.getPropertyValue(b);c===""&&!q.contains(a.ownerDocument.documentElement,a)&&(c=q.style(a,b))}if(!q.b.mc&&f&&ed.test(b)&&wa.test(c)){d=g.width;g.width=c;c=f.width;g.width=d}return c});
y.documentElement.currentStyle&&(hd=function(a,b){var c,d,f=a.currentStyle&&a.currentStyle[b],g=a.style;if(f==k&&g&&(c=g[b]))f=c;if(wa.test(f)){c=g.left;if(d=a.runtimeStyle&&a.runtimeStyle.left)a.runtimeStyle.left=a.currentStyle.left;g.left=b==="fontSize"?"1em":f;f=g.pixelLeft+"px";g.left=c;if(d)a.runtimeStyle.left=d}return f===""?"auto":f});w=gd||hd;
q.a(["height","width"],function(a,b){q.Q[b]={get:function(a,d,f){if(d)return a.offsetWidth!==0?va(a,b,f):q.Bc(a,fd,function(){return va(a,b,f)})},set:function(a,b){return cd.test(b)?b+"px":b}}});
q.b.opacity||(q.Q.opacity={get:function(a,b){return ad.test((b&&a.currentStyle?a.currentStyle.filter:a.style.filter)||"")?parseFloat(RegExp.$1)/100+"":b?"1":""},set:function(a,b){var c=a.style,d=a.currentStyle,f=q.nb(b)?"alpha(opacity="+b*100+")":"",g=d&&d.filter||c.filter||"";c.zoom=1;if(b>=1&&q.trim(g.replace($c,""))===""){c.removeAttribute("filter");if(d&&!d.filter)return}c.filter=$c.test(g)?g.replace($c,f):g+" "+f}});
q(function(){if(!q.b.tc)q.Q.marginRight={get:function(a,b){return q.Bc(a,{display:"inline-block"},function(){return b?w(a,"margin-right"):a.style.marginRight})}}});q.l&&q.l.H&&(q.l.H.hidden=function(a){var b=a.offsetHeight;return a.offsetWidth===0&&b===0||!q.b.Qd&&(a.style&&a.style.display||q.e(a,"display"))==="none"},q.l.H.visible=function(a){return!q.l.H.hidden(a)});
q.a({margin:"",padding:"",border:"Width"},function(a,b){q.Q[a+b]={expand:function(c){for(var d=typeof c==="string"?c.split(" "):[c],f={},c=0;c<4;c++)f[a+v[c]+b]=d[c]||d[c-2]||d[0];return f}}});
var id=/%20/g,Da=/\[\]$/,jd=/\r?\n/g,kd=/#.*$/,ld=/^(.*?):[ \t]*([^\r\n]*)\r?$/mg,md=/^(?:color|date|datetime|datetime-local|email|hidden|month|number|password|range|search|tel|text|time|url|week)$/i,nd=/^(?:GET|HEAD)$/,od=/^\/\//,pd=/\?/,qd=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,rd=/^(?:select|textarea)/i,ya=/\s+/,sd=/([?&])_=[^&]*/,td=/^([\w\+\.\-]+:)(?:\/\/([^\/?#:]*)(?::(\d+))?)?/,ud=q.d.load,Aa={},vd={},Z,$,wd=["*/"]+["*"];
try{Z=Oa.href}catch(xd){Z=y.createElement("a"),Z.href="",Z=Z.href}$=td.exec(Z.toLowerCase())||[];
q.d.extend({load:function(a,b,c){if(typeof a!=="string"&&ud)return ud.apply(this,arguments);if(!this.length)return this;var d=a.indexOf(" ");if(d>=0)var f=a.slice(d,a.length),a=a.slice(0,d);d="GET";if(b)if(q.g(b)){c=b;b=p}else if(typeof b==="object"){b=q.vb(b,q.M.Fc);d="POST"}var g=this;q.ka({url:a,type:d,dataType:"html",data:b,complete:function(a,b,d){d=a.responseText;if(a.xd()){a.ba(function(a){d=a});g.da(f?q("<div>").append(d.replace(qd,"")).find(f):d)}c&&g.a(c,[d,b,a])}});return this},yf:function(){return q.vb(this.Xd())},
Xd:function(){return this.map(function(){return this.elements?q.T(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||rd.test(this.nodeName)||md.test(this.type))}).map(function(a,b){var c=q(this).V();return c==k?k:q.isArray(c)?q.map(c,function(a){return{name:b.name,value:a.replace(jd,"\r\n")}}):{name:b.name,value:c.replace(jd,"\r\n")}}).get()}});
q.a("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){q.d[b]=function(a){return this.U(b,a)}});q.a(["get","post"],function(a,b){q[b]=function(a,d,f,g){if(q.g(d)){g=g||f;f=d;d=p}return q.ka({type:b,url:a,data:d,Ac:f,dataType:g})}});
q.extend({Oe:function(a,b){return q.get(a,p,b,"script")},Ne:function(a,b,c){return q.get(a,b,c,"json")},Za:function(a,b){if(b)Ba(a,q.M);else{b=a;a=q.M}Ba(a,b);return a},M:{url:Z,$b:/^(?:about|app|app\-storage|.+\-extension|file|res|widget):$/.test($[1]),global:e,type:"GET",contentType:"application/x-www-form-urlencoded; charset=UTF-8",Od:e,async:e,Ea:{xml:"application/xml, text/xml",da:"text/html",text:"text/plain",yd:"application/json, text/javascript","*":wd},ma:{xml:/xml/,da:/html/,yd:/json/},
Td:{xml:"responseXML",text:"responseText"},na:{"* text":o.le,"text html":e,"text json":q.lc,"text xml":q.Jd},kd:{o:e,url:e}},Kb:xa(Aa),Lb:xa(vd),ka:function(a,b){function c(a,b,c,n){if(F!==2){F=2;C&&clearTimeout(C);z=p;s=n||"";A.readyState=a>0?4:0;var t,u,B,n=b;if(c){var J=d,oa=A,hb=J.ma,N=J.t,pa=J.Td,G,D,O,ib;for(D in pa)D in c&&(oa[pa[D]]=c[D]);for(;N[0]==="*";){N.shift();G===p&&(G=J.sb||oa.getResponseHeader("content-type"))}if(G)for(D in hb)if(hb[D]&&hb[D].test(G)){N.unshift(D);break}if(N[0]in
c)O=N[0];else{for(D in c){if(!N[0]||J.na[D+" "+N[0]]){O=D;break}ib||(ib=D)}O=O||ib}if(O){O!==N[0]&&N.unshift(O);c=c[O]}else c=void 0}else c=p;if(a>=200&&a<300||a===304){if(d.ud){if(G=A.getResponseHeader("Last-Modified"))q.lastModified[m]=G;if(G=A.getResponseHeader("Etag"))q.jb[m]=G}if(a===304){n="notmodified";t=e}else try{G=d;G.cd&&(c=G.cd(c,G.dataType));var jb=G.t;D={};var na,Ja,Bd=jb.length,Ka,P=jb[0],ga,kb,Q,W,ha;for(na=1;na<Bd;na++){if(na===1)for(Ja in G.na)typeof Ja==="string"&&(D[Ja.toLowerCase()]=
G.na[Ja]);ga=P;P=jb[na];if(P==="*")P=ga;else if(ga!=="*"&&ga!==P){kb=ga+" "+P;Q=D[kb]||D["* "+P];if(!Q){ha=p;for(W in D){Ka=W.split(" ");if(Ka[0]===ga||Ka[0]==="*")if(ha=D[Ka[1]+" "+P]){W=D[W];W===e?Q=ha:ha===e&&(Q=W);break}}}!Q&&!ha&&q.error("No conversion from "+kb.replace(" "," to "));Q!==e&&(c=Q?Q(c):ha(W(c)))}}u=c;n="success";t=e}catch(Cd){n="parsererror";B=Cd}}else{B=n;if(!n||a){n="error";a<0&&(a=0)}}A.status=a;A.statusText=""+(b||n);t?i.Ua(f,[u,n,A]):i.tf(f,[A,n,B]);A.zc(j);j=p;ka&&g.m("ajax"+
(t?"Success":"Error"),[A,d,t?u:B]);h.sa(f,[A,n]);if(ka){g.m("ajaxComplete",[A,d]);--q.Jb||q.event.m("ajaxStop")}}}if(typeof a==="object"){b=a;a=p}var b=b||{},d=q.Za({},b),f=d.o||d,g=f!==d&&(f.nodeType||f instanceof q)?q(f):q.event,i=q.Aa(),h=q.W("once memory"),j=d.zc||{},m,n={},t={},s,u,z,C,B,F=0,ka,J,A={readyState:0,setRequestHeader:function(a,b){if(!F){var c=a.toLowerCase(),a=t[c]=t[c]||a;n[a]=b}return this},getAllResponseHeaders:function(){return F===2?s:k},getResponseHeader:function(a){var b;
if(F===2){if(!u)for(u={};b=ld.exec(s);)u[b[1].toLowerCase()]=b[2];b=u[a.toLowerCase()]}return b===p?k:b},overrideMimeType:function(a){if(!F)d.sb=a;return this},abort:function(a){a=a||"abort";z&&z.abort(a);c(0,a);return this}};i.p(A);A.Ac=A.ba;A.error=A.ra;A.complete=h.add;A.zc=function(a){if(a){var b;if(F<2)for(b in a)j[b]=[j[b],a[b]];else{b=a[A.status];A.zb(b,b)}}return this};d.url=((a||d.url)+"").replace(kd,"").replace(od,$[1]+"//");d.t=q.trim(d.dataType||"*").toLowerCase().split(ya);if(d.Z==k){B=
td.exec(d.url.toLowerCase());d.Z=!(!B||!(B[1]!=$[1]||B[2]!=$[2]||(B[3]||(B[1]==="http:"?80:443))!=($[3]||($[1]==="http:"?80:443))))}if(d.data&&d.Od&&typeof d.data!=="string")d.data=q.vb(d.data,d.Fc);za(Aa,d,b,A);if(F===2)return l;ka=d.global;d.type=d.type.toUpperCase();d.mb=!nd.test(d.type);ka&&q.Jb++===0&&q.event.m("ajaxStart");if(!d.mb){if(d.data){d.url=d.url+((pd.test(d.url)?"&":"?")+d.data);delete d.data}m=d.url;if(d.G===l){B=q.now();var oa=d.url.replace(sd,"$1_="+B);d.url=oa+(oa===d.url?(pd.test(d.url)?
"&":"?")+"_="+B:"")}}(d.data&&d.mb&&d.contentType!==l||b.contentType)&&A.setRequestHeader("Content-Type",d.contentType);if(d.ud){m=m||d.url;q.lastModified[m]&&A.setRequestHeader("If-Modified-Since",q.lastModified[m]);q.jb[m]&&A.setRequestHeader("If-None-Match",q.jb[m])}A.setRequestHeader("Accept",d.t[0]&&d.Ea[d.t[0]]?d.Ea[d.t[0]]+(d.t[0]!=="*"?", "+wd+"; q=0.01":""):d.Ea["*"]);for(J in d.headers)A.setRequestHeader(J,d.headers[J]);if(d.Uc&&(d.Uc.call(f,A,d)===l||F===2)){A.abort();return l}for(J in{Ac:1,
error:1,complete:1})A[J](d[J]);if(z=za(vd,d,b,A)){A.readyState=1;ka&&g.m("ajaxSend",[A,d]);d.async&&d.timeout>0&&(C=setTimeout(function(){A.abort("timeout")},d.timeout));try{F=1;z.send(n,c)}catch(pa){if(F<2)c(-1,pa);else throw pa;}}else c(-1,"No Transport");return A},vb:function(a,b){function c(a,b){b=q.g(b)?b():b;d[d.length]=encodeURIComponent(a)+"="+encodeURIComponent(b)}var d=[];if(b===p)b=q.M.Fc;if(q.isArray(a)||a.v&&!q.Ma(a))q.a(a,function(){c(this.name,this.value)});else for(var f in a)Ca(f,
a[f],b,c);return d.join("&").replace(id,"+")}});q.extend({Jb:0,lastModified:{},jb:{}});var yd=q.now(),zd=/(\=)\?(&|$)|\?\?/i;q.Za({qb:"callback",Pa:function(){return q.expando+"_"+yd++}});
q.Kb("json jsonp",function(a,b,c){b=typeof a.data==="string"&&/^application\/x\-www\-form\-urlencoded/.test(a.contentType);if(a.t[0]==="jsonp"||a.qb!==l&&(zd.test(a.url)||b&&zd.test(a.data))){var d,f=a.Pa=q.g(a.Pa)?a.Pa():a.Pa,g=o[f],i=a.url,h=a.data,j="$1"+f+"$2";if(a.qb!==l){i=i.replace(zd,j);if(a.url===i){b&&(h=h.replace(zd,j));a.data===h&&(i=i+((/\?/.test(i)?"&":"?")+a.qb+"="+f))}}a.url=i;a.data=h;o[f]=function(a){d=[a]};c.Pc(function(){o[f]=g;if(d&&q.g(g))o[f](d[0])});a.na["script json"]=function(){d||
q.error(f+" was not called");return d[0]};a.t[0]="json";return"script"}});q.Za({Ea:{Vd:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},ma:{Vd:/javascript|ecmascript/},na:{"text script":function(a){q.Wb(a);return a}}});q.Kb("script",function(a){if(a.G===p)a.G=l;if(a.Z){a.type="GET";a.global=l}});
q.Lb("script",function(a){if(a.Z){var b,c=y.head||y.getElementsByTagName("head")[0]||y.documentElement;return{send:function(d,f){b=y.createElement("script");b.async="async";if(a.Wd)b.charset=a.Wd;b.src=a.url;b.onload=b.onreadystatechange=function(a,d){if(d||!b.readyState||/loaded|complete/.test(b.readyState)){b.onload=b.onreadystatechange=k;c&&b.parentNode&&c.removeChild(b);b=p;d||f(200,"success")}};c.insertBefore(b,c.firstChild)},abort:function(){if(b)b.onload(0,1)}}}});
var Dd=o.ActiveXObject?function(){for(var a in Ad)Ad[a](0,1)}:l,Ed=0,Ad;q.M.Hc=o.ActiveXObject?function(){var a;if(!(a=!this.$b&&Ea()))a:{try{a=new o.ActiveXObject("Microsoft.XMLHTTP");break a}catch(b){}a=void 0}return a}:Ea;var Fd=q.M.Hc();q.extend(q.b,{ka:!!Fd,ad:!!Fd&&"withCredentials"in Fd});
q.b.ka&&q.Lb(function(a){if(!a.Z||q.b.ad){var b;return{send:function(c,d){var f=a.Hc(),g,i;a.he?f.open(a.type,a.url,a.async,a.he,a.Kd):f.open(a.type,a.url,a.async);if(a.Ic)for(i in a.Ic)f[i]=a.Ic[i];a.sb&&f.overrideMimeType&&f.overrideMimeType(a.sb);!a.Z&&!c["X-Requested-With"]&&(c["X-Requested-With"]="XMLHttpRequest");try{for(i in c)f.setRequestHeader(i,c[i])}catch(h){}f.send(a.mb&&a.data||k);b=function(c,h){var i,t,s,u,z;try{if(b&&(h||f.readyState===4)){b=p;if(g){f.onreadystatechange=q.hc;Dd&&delete Ad[g]}if(h)f.readyState!==
4&&f.abort();else{i=f.status;s=f.getAllResponseHeaders();u={};if((z=f.responseXML)&&z.documentElement)u.xml=z;try{u.text=f.responseText}catch(C){}try{t=f.statusText}catch(B){t=""}!i&&a.$b&&!a.Z?i=u.text?200:404:i===1223&&(i=204)}}}catch(F){h||d(-1,F)}u&&d(i,t,u,s)};if(!a.async||f.readyState===4)b();else{g=++Ed;if(Dd){if(!Ad){Ad={};q(o).Mf(Dd)}Ad[g]=b}f.onreadystatechange=b}},abort:function(){b&&b(0,1)}}}});
var Ma={},E,H,Gd=/^(?:toggle|show|hide)$/,Hd=/^([+\-]=)?([\d+.\-]+)([a-z%]*)$/i,Id,Ia=[["height","marginTop","marginBottom","paddingTop","paddingBottom"],["width","marginLeft","marginRight","paddingLeft","paddingRight"],["opacity"]],Ha;
q.d.extend({show:function(a,b,c){if(a||a===0)return this.la(x("show",3),a,b,c);for(var c=0,d=this.length;c<d;c++){a=this[c];if(a.style){b=a.style.display;if(!q.c(a,"olddisplay")&&b==="none")b=a.style.display="";(b===""&&q.e(a,"display")==="none"||!q.contains(a.ownerDocument.documentElement,a))&&q.c(a,"olddisplay",La(a.nodeName))}}for(c=0;c<d;c++){a=this[c];if(a.style){b=a.style.display;if(b===""||b==="none")a.style.display=q.c(a,"olddisplay")||""}}return this},ca:function(a,b,c){if(a||a===0)return this.la(x("hide",
3),a,b,c);for(var c=0,d=this.length;c<d;c++){a=this[c];if(a.style){b=q.e(a,"display");b!=="none"&&!q.c(a,"olddisplay")&&q.c(a,"olddisplay",b)}}for(c=0;c<d;c++)if(this[c].style)this[c].style.display="none";return this},Nc:q.d.toggle,toggle:function(a,b,c){var d=typeof a==="boolean";q.g(a)&&q.g(b)?this.Nc.apply(this,arguments):a==k||d?this.a(function(){var b=d?a:q(this).ta(":hidden");q(this)[b?"show":"hide"]()}):this.la(x("toggle",3),a,b,c);return this},Ie:function(a,b,c,d){return this.filter(":hidden").e("opacity",
0).show().end().la({opacity:b},a,c,d)},la:function(a,b,c,d){function f(){g.k===l&&q.Lc(this);var b=q.extend({},g),c=this.nodeType===1,d=c&&q(this).ta(":hidden"),f,n,t,s,u;b.N={};for(t in a){f=q.P(t);if(t!==f){a[f]=a[t];delete a[t]}if((n=q.Q[f])&&"expand"in n){s=n.expand(a[f]);delete a[f];for(t in s)t in a||(a[t]=s[t])}}for(f in a){n=a[f];if(q.isArray(n)){b.N[f]=n[1];n=a[f]=n[0]}else b.N[f]=b.$d&&b.$d[f]||b.ib||"swing";if(n==="hide"&&d||n==="show"&&!d)return b.complete.call(this);if(c&&(f==="height"||
f==="width")){b.overflow=[this.style.overflow,this.style.overflowX,this.style.overflowY];if(q.e(this,"display")==="inline"&&q.e(this,"float")==="none")!q.b.Zb||La(this.nodeName)==="inline"?this.style.display="inline-block":this.style.zoom=1}}if(b.overflow!=k)this.style.overflow="hidden";for(t in a){c=new q.n(this,b,t);n=a[t];if(Gd.test(n))if(f=q.c(this,"toggle"+t)||(n==="toggle"?d?"show":"hide":0)){q.c(this,"toggle"+t,f==="show"?"hide":"show");c[f]()}else c[n]();else{f=Hd.exec(n);s=c.oa();if(f){n=
parseFloat(f[2]);u=f[3]||(q.fb[t]?"":"px");if(u!=="px"){q.style(this,t,(n||1)+u);s=(n||1)/c.oa()*s;q.style(this,t,s+u)}f[1]&&(n=(f[1]==="-="?-1:1)*n+s);c.pa(s,n,u)}else c.pa(s,n,"")}}return e}var g=q.speed(b,c,d);if(q.La(a))return this.a(g.complete,[l]);a=q.extend({},a);return g.k===l?this.a(f):this.k(g.k,f)},stop:function(a,b,c){if(typeof a!=="string"){c=b;b=a;a=p}b&&a!==l&&this.k(a||"fx",[]);return this.a(function(){var b,f=l,g=q.Xa,i=q.c(this);c||q.Ib(e,this);if(a==k)for(b in i){if(i[b]&&i[b].stop&&
b.indexOf(".run")===b.length-4){var h=i[b];q.u(this,b,e);h.stop(c)}}else if(i[b=a+".run"]&&i[b].stop){i=i[b];q.u(this,b,e);i.stop(c)}for(b=g.length;b--;)if(g[b].f===this&&(a==k||g[b].k===a)){if(c)g[b](e);else g[b].Ud();f=e;g.splice(b,1)}(!c||!f)&&q.$(this,a)})}});q.a({Af:x("show",1),Cf:x("hide",1),Bf:x("toggle",1),Ge:{opacity:"show"},He:{opacity:"hide"},Je:{opacity:"toggle"}},function(a,b){q.d[a]=function(a,d,f){return this.la(b,a,d,f)}});
q.extend({speed:function(a,b,c){var d=a&&typeof a==="object"?q.extend({},a):{complete:c||!c&&b||q.g(a)&&a,duration:a,ib:c&&b||b&&!q.g(b)&&b};d.duration=q.n.D?0:typeof d.duration==="number"?d.duration:d.duration in q.n.Wa?q.n.Wa[d.duration]:q.n.Wa.F;if(d.k==k||d.k===e)d.k="fx";d.ic=d.complete;d.complete=function(a){q.g(d.ic)&&d.ic.call(this);d.k?q.$(this,d.k):a!==l&&q.Ib(this)};return d},ib:{Xe:function(a){return a},Gf:function(a){return-Math.cos(a*Math.PI)/2+0.5}},Xa:[],n:function(a,b,c){this.options=
b;this.f=a;this.h=c;b.Qa=b.Qa||{}}});
q.n.prototype={update:function(){this.options.step&&this.options.step.call(this.f,this.now,this);(q.n.step[this.h]||q.n.step.F)(this)},oa:function(){if(this.f[this.h]!=k&&(!this.f.style||this.f.style[this.h]==k))return this.f[this.h];var a,b=q.e(this.f,this.h);return isNaN(a=parseFloat(b))?!b||b==="auto"?0:b:a},pa:function(a,b,c){function d(a){return f.step(a)}var f=this,g=q.n;this.startTime=Ha||Fa();this.end=b;this.now=this.start=a;this.wb=this.state=0;this.Cb=c||this.Cb||(q.fb[this.h]?"":"px");
d.k=this.options.k;d.f=this.f;d.Ud=function(){q.c(f.f,"fxshow"+f.h)===p&&(f.options.ca?q.c(f.f,"fxshow"+f.h,f.start):f.options.show&&q.c(f.f,"fxshow"+f.h,f.end))};d()&&(q.Xa.push(d)&&!Id)&&(Id=setInterval(g.ee,g.vd))},show:function(){var a=q.c(this.f,"fxshow"+this.h);this.options.Qa[this.h]=a||q.style(this.f,this.h);this.options.show=e;a!==p?this.pa(this.oa(),a):this.pa(this.h==="width"||this.h==="height"?1:0,this.oa());q(this.f).show()},ca:function(){this.options.Qa[this.h]=q.c(this.f,"fxshow"+this.h)||
q.style(this.f,this.h);this.options.ca=e;this.pa(this.oa(),0)},step:function(a){var b,c=Ha||Fa(),d=e,f=this.f,g=this.options;if(a||c>=g.duration+this.startTime){this.now=this.end;this.wb=this.state=1;this.update();g.N[this.h]=e;for(b in g.N)g.N[b]!==e&&(d=l);if(d){g.overflow!=k&&!q.b.xc&&q.a(["","X","Y"],function(a,b){f.style["overflow"+b]=g.overflow[a]});g.ca&&q(f).ca();if(g.ca||g.show)for(b in g.N){q.style(f,b,g.Qa[b]);q.u(f,"fxshow"+b,e);q.u(f,"toggle"+b,e)}if(a=g.complete){g.complete=l;a.call(f)}}return l}if(g.duration==
Infinity)this.now=c;else{a=c-this.startTime;this.state=a/g.duration;this.wb=q.ib[g.N[this.h]](this.state,a,0,1,g.duration);this.now=this.start+(this.end-this.start)*this.wb}this.update();return e}};
q.extend(q.n,{ee:function(){for(var a,b=q.Xa,c=0;c<b.length;c++){a=b[c];!a()&&b[c]===a&&b.splice(c--,1)}b.length||q.n.stop()},vd:13,stop:function(){clearInterval(Id);Id=k},Wa:{Df:600,Ke:200,F:400},step:{opacity:function(a){q.style(a.f,"opacity",a.now)},F:function(a){a.f.style&&a.f.style[a.h]!=k?a.f.style[a.h]=a.now+a.Cb:a.f[a.h]=a.now}}});q.a(Ia.concat.apply([],Ia),function(a,b){b.indexOf("margin")&&(q.n.step[b]=function(a){q.style(a.f,b,Math.max(0,a.now)+a.Cb)})});
q.l&&q.l.H&&(q.l.H.qe=function(a){return q.R(q.Xa,function(b){return a===b.f}).length});var Jd,Kd=/^t(?:able|d|h)$/i,Ld=/^(?:body|html)$/i;
Jd="getBoundingClientRect"in y.documentElement?function(a,b,c,d){try{d=a.getBoundingClientRect()}catch(f){}if(!d||!q.contains(c,a))return d?{top:d.top,left:d.left}:{top:0,left:0};a=b.body;b=Na(b);return{top:d.top+(b.pageYOffset||q.b.X&&c.scrollTop||a.scrollTop)-(c.clientTop||a.clientTop||0),left:d.left+(b.pageXOffset||q.b.X&&c.scrollLeft||a.scrollLeft)-(c.clientLeft||a.clientLeft||0)}}:function(a,b,c){var d,f=a.offsetParent,g=b.body;d=(b=b.defaultView)?b.getComputedStyle(a,k):a.currentStyle;for(var i=
a.offsetTop,h=a.offsetLeft;(a=a.parentNode)&&a!==g&&a!==c;){if(q.b.Ub&&d.position==="fixed")break;d=b?b.getComputedStyle(a,k):a.currentStyle;i=i-a.scrollTop;h=h-a.scrollLeft;if(a===f){i=i+a.offsetTop;h=h+a.offsetLeft;if(q.b.fd&&(!q.b.ed||!Kd.test(a.nodeName))){i=i+(parseFloat(d.borderTopWidth)||0);h=h+(parseFloat(d.borderLeftWidth)||0)}f=a.offsetParent}if(q.b.be&&d.overflow!=="visible"){i=i+(parseFloat(d.borderTopWidth)||0);h=h+(parseFloat(d.borderLeftWidth)||0)}}if(d.position==="relative"||d.position===
"static"){i=i+g.offsetTop;h=h+g.offsetLeft}if(q.b.Ub&&d.position==="fixed"){i=i+Math.max(c.scrollTop,g.scrollTop);h=h+Math.max(c.scrollLeft,g.scrollLeft)}return{top:i,left:h}};q.d.offset=function(a){if(arguments.length)return a===p?this:this.a(function(b){q.offset.Zd(this,a,b)});var b=this[0],c=b&&b.ownerDocument;return!c?k:b===c.body?q.offset.Vc(b):Jd(b,c,c.documentElement)};
q.offset={Vc:function(a){var b=a.offsetTop,c=a.offsetLeft;if(q.b.gd){b=b+(parseFloat(q.e(a,"marginTop"))||0);c=c+(parseFloat(q.e(a,"marginLeft"))||0)}return{top:b,left:c}},Zd:function(a,b,c){var d=q.e(a,"position");if(d==="static")a.style.position="relative";var f=q(a),g=f.offset(),i=q.e(a,"top"),h=q.e(a,"left"),j={},m={};if((d==="absolute"||d==="fixed")&&q.ea("auto",[i,h])>-1){m=f.position();d=m.top;h=m.left}else{d=parseFloat(i)||0;h=parseFloat(h)||0}q.g(b)&&(b=b.call(a,c,g));if(b.top!=k)j.top=b.top-
g.top+d;if(b.left!=k)j.left=b.left-g.left+h;"using"in b?b.Pf.call(a,j):f.e(j)}};
q.d.extend({position:function(){if(!this[0])return k;var a=this[0],b=this.offsetParent(),c=this.offset(),d=Ld.test(b[0].nodeName)?{top:0,left:0}:b.offset();c.top=c.top-(parseFloat(q.e(a,"marginTop"))||0);c.left=c.left-(parseFloat(q.e(a,"marginLeft"))||0);d.top=d.top+(parseFloat(q.e(b[0],"borderTopWidth"))||0);d.left=d.left+(parseFloat(q.e(b[0],"borderLeftWidth"))||0);return{top:c.top-d.top,left:c.left-d.left}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||y.body;a&&
!Ld.test(a.nodeName)&&q.e(a,"position")==="static";)a=a.offsetParent;return a})}});q.a({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var c=/Y/.test(b);q.d[a]=function(d){return q.w(this,function(a,d,i){var h=Na(a);if(i===p)return h?b in h?h[b]:q.b.X&&h.document.documentElement[d]||h.document.body[d]:a[d];h?h.scrollTo(!c?i:q(h).scrollLeft(),c?i:q(h).scrollTop()):a[d]=i},a,d,arguments.length,k)}});
q.a({ke:"height",me:"width"},function(a,b){var c="client"+a,d="scroll"+a,f="offset"+a;q.d["inner"+a]=function(){var a=this[0];return a?a.style?parseFloat(q.e(a,b,"padding")):this[b]():k};q.d["outer"+a]=function(a){var c=this[0];return c?c.style?parseFloat(q.e(c,b,a?"margin":"border")):this[b]():k};q.d[b]=function(a){return q.w(this,function(a,b,g){if(q.S(a)){b=a.document;a=b.documentElement[c];return q.b.X&&a||b.body&&b.body[c]||a}if(a.nodeType===9){b=a.documentElement;return b[c]>=b[d]?b[c]:Math.max(a.body[d],
b[d],a.body[f],b[f])}if(g===p){a=q.e(a,b);b=parseFloat(a);return q.nb(b)?b:a}q(a).e(b,g)},b,a,arguments.length,k)}});o.v=o.ne=q;"function"===typeof define&&(define.Qc&&define.Qc.v)&&define("aQuery",[],function(){return q});